UI : Minor ui fixes and localisation
open-metadata/OpenMetadata pull request #10001
Opened 2023-01-30 10:17 UTC by Ashish8689

### Describe your changes :

- Deprecated Button change to Antd Button
- Localisation in the service page

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<img width="301" alt="image" src="https://user-images.githubusercontent.com/66266464/215449775-a9573beb-ee8d-4430-8daf-ce4b83f2984e.png">
<img width="336" alt="image" src="https://user-images.githubusercontent.com/66266464/215449247-bbc527e6-a116-4724-be88-94180b0270a7.png">
<img width="336" alt="image" src="https://user-images.githubusercontent.com/66266464/215449316-e808e1fc-e308-4a0f-8796-f52e72cfeff4.png">
<img width="481" alt="image" src="https://user-images.githubusercontent.com/66266464/215449519-cd6759a7-3e67-4e35-866a-15630650dd6a.png">
<img width="301" alt="image" src="https://user-images.githubusercontent.com/66266464/215449577-7321a91f-c36c-4a1e-a713-1480902698f1.png">

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

2023-01-31 13:27 UTC, ShaileshParmar11 reviewed
left few comments

2023-01-31 13:27 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
> +                        : NO_PERMISSION_FOR_ACTION
is it necessary to call `getCustomPageHeader()` function in tooltip? it will be called in every render!

2023-01-31 13:27 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
> +                  }>
same here!

2023-01-31 13:27 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/pages/tags/index.tsx
> +                      }}>
```suggestion
                      onClick={deleteTagHandler}>
```

2023-01-31 16:01 UTC, chirag-madlani submitted a review, later dismissed

2023-01-31 16:10 UTC, Ashish8689 commented
@chirag-madlani We have admin create permission on buttons, so to let user know why it is disabled tooltip is used.

2023-02-01 04:34 UTC, ShaileshParmar11 approved these changes

2023-02-01 04:34 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/pages/CustomPropertiesPageV1/CustomPropertiesPageV1.tsx
> +        break;
can we use -> useMemo? instead of useState and useEffect?

2023-02-01 04:36 UTC, ShaileshParmar11 requested changes
left one comment

2023-02-01 05:17 UTC, Ashish8689 commented
@ShaileshParmar11  Done!

2023-02-01 05:38 UTC, ShaileshParmar11 approved these changes

2023-02-01 12:04 UTC, merged