Add support for AssumeRole for AWS
open-metadata/OpenMetadata pull request #10417
Opened 2023-03-03 11:03 UTC by ulixius9

### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2023-03-03 16:15 UTC, akash-jain-10 requested changes

2023-03-03 16:15 UTC, akash-jain-10 commented on openmetadata-spec/src/main/resources/json/schema/security/credentials/awsCredentials.json
> +      "description": "The name of a profile to create the boto session.",
Let's update the description here!

```suggestion
      "description": "The name of a profile to use with the boto session.",
```

2023-03-03 16:15 UTC, akash-jain-10 commented on openmetadata-spec/src/main/resources/json/schema/security/credentials/awsCredentials.json
> +      "description": "The name of a profile to create the boto session.",
Our code will not be responsible for creating Profiles rather using them. The common use-case I can think of from AWS is with custom Airflow Installations where the associated workers will have multiple profiles configured with AWS and they would like to pick one!

2023-03-06 03:27 UTC, akash-jain-10 approved these changes

2023-03-06 07:12 UTC, ayush-shah reviewed
Py checkstyle failing, can you take a look?

2023-03-08 10:13 UTC, OnkarVO7 approved these changes

2023-03-08 10:13 UTC, merged