Added flag for overriding owners
open-metadata/OpenMetadata pull request #10425
Opened 2023-03-03 17:04 UTC by NiharDoshi99

### Describe your changes :

I worked on adding flag for overriding owners for dashboard
Fix : #10406 

### Type of change :

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

2023-03-03 17:11 UTC, nahuelverdugo reviewed
@NiharDoshi99 should we update the documentation with this change?

2023-03-03 18:58 UTC, NiharDoshi99 commented
> @NiharDoshi99 should we update the documentation with this change?

Done

2023-03-03 19:42 UTC, harshach commented
@pmbrull @NiharDoshi99 @nahuelverdugo 
We should look at the use cases better here.

1. There is ownership is set, user would like to fetch the ownership from the source
2. Once the default ownership is propagated, others might override by setting their ownership from the OpenMetadata
3. Flag is to preserve the ownership or source

Essentially this flag will determine
1. If the ownership is set at OpenMetadata preserve that or override from the source

Users can choose which one they prefer in storing the metadata ownership/description etc..

2023-03-09 14:00 UTC, OnkarVO7 requested changes
Few comments rest looks good

2023-03-09 14:00 UTC, OnkarVO7 commented on ingestion/src/metadata/ingestion/source/dashboard/dashboard_service.py
> +                processor="yield_owner",
We are not exactly yielding anything here. Maybe change the method name to `process_owner`

2023-03-09 14:00 UTC, OnkarVO7 commented on openmetadata-docs/content/connectors/dashboard/domo-dashboard/cli.md
> +- `overrideOwner`: Flag to override current owner by new owner, if found during metadata ingestion
```suggestion
- `overrideOwner`: Flag to override current owner by new owner from source, if found during metadata ingestion
```

2023-03-10 06:15 UTC, OnkarVO7 approved these changes

2023-03-10 09:03 UTC, ShaileshParmar11 approved these changes
UI side looks good!

2023-03-10 09:22 UTC, OnkarVO7 approved these changes

2023-03-10 09:31 UTC, merged