Feat: Change UI of ES error placeholder
open-metadata/OpenMetadata pull request #1044
Opened 2021-11-03 14:04 UTC by ShaileshParmar11

### Describe your changes :

Changes:-
- Change UI of Error placeholder for ES
- Change error handling scenarios for the Landing page
- Change error handling scenarios for the explore page

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
- index missing
![image](https://user-images.githubusercontent.com/71748675/140073876-f639dff4-23f1-47c7-903f-7c218cd4cffb.png)
![image](https://user-images.githubusercontent.com/71748675/140074069-aa719a98-b8bd-4d1c-9f8e-e26fbe4996c1.png)
![image](https://user-images.githubusercontent.com/71748675/140074139-620a51d2-6c87-4721-8025-b5e1e5183b7a.png)

- connection refuced
![image](https://user-images.githubusercontent.com/71748675/140074425-76115346-2faf-4f08-8b84-b0cef9564a02.png)
![image](https://user-images.githubusercontent.com/71748675/140074511-0b0e9c12-be54-4309-8a31-ef7f658f45f2.png)

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2021-11-03 15:22 UTC, harshach commented
@ShaileshParmar11 This looks great!! Thanks

2021-11-07 07:28 UTC, Sachin-chaurasiya commented on catalog-rest-service/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
> +    const entityList = [
this should be` entityIndexList`.

2021-11-07 07:30 UTC, Sachin-chaurasiya requested changes
One minor change requested otherwise LGTM.

2021-11-08 03:28 UTC, ShaileshParmar11 commented on catalog-rest-service/src/main/resources/ui/src/pages/MyDataPage/MyDataPage.component.tsx
> +    const entityList = [
changes made

2021-11-08 04:36 UTC, Sachin-chaurasiya approved these changes

2021-11-08 08:07 UTC, merged