Fix #10814: Improve parsing logic for union fields in topic
open-metadata/OpenMetadata pull request #10836
Opened 2023-03-30 06:07 UTC by ulixius9

### Describe your changes:

Fix #10814: Improve parsing logic for union fields in topic

I worked on ... because ...

#
### Type of change:

- [x] Bug fix
- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2023-03-31 09:12 UTC, NiharDoshi99 approved these changes

2023-03-31 09:14 UTC, OnkarVO7 approved these changes

2023-03-31 14:07 UTC, NiharDoshi99 approved these changes

2023-03-31 14:07 UTC, OnkarVO7 approved these changes

2023-03-31 14:08 UTC, shahsank3t submitted a review, later dismissed

2023-03-31 14:14 UTC, ayush-shah requested changes

2023-03-31 14:14 UTC, ayush-shah commented on openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/TopicRepository.java
> +      String field = getSchemaField(original, origField, FIELD_DISPLAY_NAME);
```suggestion
      String field = getSchemaField(original, origField, FIELD_DATA_DISPLAY_TYPE);
```

Define FIELD_DATA_DISPLAY_TYPE Field here

2023-04-01 05:39 UTC, ayush-shah commented
Merging it as requested changes are resolved and tested

2023-04-01 05:40 UTC, merged