Impalaconnection
open-metadata/OpenMetadata pull request #11151
Opened 2023-04-19 15:10 UTC by ksirmons

### Describe your changes:

Fixes <issue-number>

I worked on impala connection because there are enough differences between it and hive that its own connection was warranted, 

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2023-04-19 16:45 UTC, ksirmons commented on ingestion/src/metadata/ingestion/source/database/impala/connection.py
> +    print(url)
I'll remove the print statement and push back to my repo

2023-04-19 17:02 UTC, ksirmons commented on ingestion/setup.py
> +        *COMMONS["impala"],
I am not too sure what you are saying here.  I was following the pattern that was setup in Hive, but I didn't fully understand why that pattern was there.  

One thing that may be missing in this setup is the kerberos option.  

`pip install impyla[kerberos]`

Let me know how you want the pip packages to work and I will happily make the changes..

Keith

2023-04-20 07:33 UTC, Sachin-chaurasiya requested changes
@ksirmons, There is some conflict, please resolve it. Left a few comments, thanks

2023-04-20 07:33 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Impala/fields/authOptions.md
Hello @ksirmons, Thanks for the contribution, this structure is deprecated and we are following a new structure, you can check it out [here](https://github.com/open-metadata/OpenMetadata/tree/main/openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database).

Everything is in a single file now.

2023-04-20 14:22 UTC, ksirmons commented on openmetadata-ui/src/main/resources/ui/public/locales/en-US/Database/Impala/fields/authOptions.md
Updated documentation to a single file

2023-04-21 07:57 UTC, pmbrull approved these changes

2023-04-21 07:57 UTC, merged