Issue 10805 redshift e2e
open-metadata/OpenMetadata pull request #11169
Opened 2023-04-20 16:23 UTC by TeddyCr

E2E Tests for redshift.

2023-04-20 16:24 UTC, pmbrull submitted a review, later dismissed

2023-04-20 17:04 UTC, nahuelverdugo requested changes
We have to update https://github.com/open-metadata/OpenMetadata/blob/main/.github/workflows/py-cli-e2e-tests.yml. We need to add the env vars and the test we want to run.

2023-04-21 06:02 UTC, akash-jain-10 approved these changes

2023-04-21 06:55 UTC, nahuelverdugo approved these changes

2023-04-21 06:55 UTC, merged