fix(ui): fix the placeholder issue while applying filter in entity
open-metadata/OpenMetadata pull request #11529
Opened 2023-05-10 14:24 UTC by Ashish8689

### Describe your changes:

- I worked on fixing  the placeholder issue while applying a any type of filter in the entity

<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/a81dba1e-da41-415c-a9b2-fec134ce5af8">
<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/db27df35-40ac-4688-8673-94980be1b4dd">
<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/d1813410-c5e1-4164-80db-4dadc55d8aa2">
<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/12baaeca-cd80-48ed-bc62-0937c08678ed">
<img width="1440" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/251a2e6b-5bf8-475b-8935-97d06f40863e">

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2023-05-10 14:30 UTC, ShaileshParmar11 submitted a review, later dismissed

2023-05-10 14:48 UTC, karanh37 approved these changes

2023-05-11 05:22 UTC, karanh37 requested changes
Sonar failing

2023-05-12 09:54 UTC, karanh37 approved these changes

2023-05-12 09:56 UTC, chirag-madlani approved these changes

2023-05-12 09:56 UTC, merged