Fixes #12129 : enhance bigquery sample data query
open-metadata/OpenMetadata pull request #12130
Opened 2023-06-23 17:24 UTC by duongphannamhung

### Describe your changes:
read more with my enhancement issue #12129 

Another concern: in my opinion, profiler fetching data with `row count` type will also be executed with default percent to get the efficiency query and then limit with `row count`. It would be nice for a big table, but not really good for the really small one (< 500 rows). Hope to hear your advice for better solution.

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2023-06-25 17:40 UTC, harshach commented
Thanks @duongphannamhung for the contribution. We will review the PR cc @TeddyCr

2023-06-25 17:41 UTC, harshach commented on ingestion/src/metadata/profiler/interface/sqlalchemy/profiler_interface.py
> +        if self.service_connection_config.type.value == "BigQuery":
instead of having if else here, it would be better to have overriding capabilities with-in each connector

2023-06-26 12:20 UTC, TeddyCr commented on ingestion/src/metadata/profiler/processor/sqlalchemy/sampler_models.py
If we want to add this we should:
1. define it as an interface (not implement methods)
2. Define what would be the common interface across sampler objects and align the existing one (pandas and sqlalchemy) as far as method names go.

2023-06-26 12:22 UTC, TeddyCr commented on ingestion/src/metadata/profiler/processor/sqlalchemy/bigquery_sampler.py
> +class BigQuerySampler(Sampler, SamplerProtocol):
This should only inherit from `Sampler`

2023-06-26 12:33 UTC, TeddyCr commented on ingestion/src/metadata/profiler/interface/sqlalchemy/profiler_interface.py
Instead of modifying this base interface class we should
1. Consolidate the `Sampler()` instantiation object in `profiler_interface.py`. We instantiate the object on ln. 391, 525, and 568. Instead of explicitly calling the object there we should define a method (e.g. `_instantiate_sampler(...)` that will instantiate a sampler object
2.  create a bigquery interface in `sqlalchemy/bigquery/profiler_interface.py` `BigQueryProfilerInterface` with `_profiler_type: str = "bigquery"`. 
3. override the `_instantiate_sampler(...)` to return a `BigQuerySampler()` object (in `BigQueryInterface`).
4. In `source/bigquery/profiler_source.py` override `create_profiler_interface` to something like below
```python
    def create_profiler_interface(
        self,
        entity: Table,
        table_config: Optional[TableConfig],
    ) -> Union[SQAProfilerInterface, PandasProfilerInterface]:
        """Create sqlalchemy profiler interface"""
        profiler_interface: BigQueryInterface = ProfilerProtocol.create(
            "bigquery",
            entity,
            table_config,
            self.source_config,
            self.service_conn_config,
            self.ometa_client,
            sqa_metadata=self.sqa_metadata,
        )  # type: ignore

        self.interface = profiler_interface
        return self.interface
```

2023-06-26 12:35 UTC, TeddyCr commented on ingestion/src/metadata/profiler/processor/sqlalchemy/bigquery_sampler.py
> +    _sampler_type = "BigQuery"
This should not be needed

2023-06-26 12:35 UTC, TeddyCr commented on ingestion/src/metadata/profiler/processor/sqlalchemy/sampler.py
> +    _sampler_type = "Default"
This should not be needed

2023-06-26 12:37 UTC, TeddyCr requested changes
Thank you for opening the PR ❤️ I have added some comments. Let me know if you need help or have questions. More than happy to help

2023-06-27 04:26 UTC, duongphannamhung commented on ingestion/src/metadata/profiler/interface/sqlalchemy/profiler_interface.py
thanks, @TeddyCr , super clear idea. I've already upgraded the old code and feel more sustainable with these new ones. Hope it's working out.

2023-06-27 06:35 UTC, TeddyCr commented
@duongphannamhung thank you for the changes. Could you rebase from main and run `make py_format` and `make py_format_check` please?

2023-06-28 06:21 UTC, TeddyCr commented
Thank @duongphannamhung we'll merge this after 1.1.0 release to have it available in 1.1.1 🙂

2023-06-29 03:04 UTC, duongphannamhung commented
I've just modified name of method `get_sample_query` -> `get_bq_sample_query`. Cause of method `random_sample` which gets Table Profile still have to use `get_sample_query` to convert to sqlalchemy structure. 

In sqlalchemy 2.0 it has `tablesample` but 1.4 current don't. Hope a bump for little more straightforward current random sample query.  
https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.tablesample

2023-07-03 13:08 UTC, TeddyCr requested changes

2023-07-03 13:08 UTC, TeddyCr commented on ingestion/src/metadata/profiler/source/bigquery/profiler_source.py
> +        profiler_interface: BigQueryProfilerSource = ProfilerProtocol.create(
@duongphannamhung this needs to be `BigQueryProfilerInterface`. Once this is changed we can merge it

2023-07-04 06:37 UTC, TeddyCr approved these changes

2023-07-04 06:37 UTC, merged