test(ui): table details component
open-metadata/OpenMetadata pull request #12278
Opened 2023-07-04 12:00 UTC by chirag-madlani

### Describe your changes:

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2023-08-01 09:21 UTC, karanh37 submitted a review, later dismissed

2023-09-04 09:01 UTC, Ashish8689 requested changes

2023-09-04 09:07 UTC, Ashish8689 commented on openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicSchema/TopicSchema.tsx
>              <Tag>{messageSchema?.schemaType ?? ''}</Tag>
but if the `schemaType` is not present then it will not satisfy the condition and not enter the block right?

2023-09-04 09:12 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TopicDetails/TopicSchema/TopicSchema.tsx
>              <Tag>{messageSchema?.schemaType ?? ''}</Tag>
Yes that's expected, So we will show schemaType only if it's present in the data

2023-09-04 12:06 UTC, Ashish8689 approved these changes

2023-09-04 13:50 UTC, merged