chore(client): new UI for the tier-card
open-metadata/OpenMetadata pull request #12536
Opened 2023-07-21 06:35 UTC by Abhishek332

### **Old UI**
<img width="1440" alt="Screenshot 2023-07-21 at 12 04 15 PM" src="https://github.com/open-metadata/OpenMetadata/assets/80886271/ff66ff82-52e0-4c7e-b4e7-77efe9ed0749">

### **New UI**
<img width="1440" alt="Screenshot 2023-07-21 at 12 04 20 PM" src="https://github.com/open-metadata/OpenMetadata/assets/80886271/0f36d9b4-1486-404b-b710-b22e205984b0">

2023-07-21 06:38 UTC, Ashish8689 commented on openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/tier-card.style.less
> +  //   }
remove this commented code.

2023-07-21 06:40 UTC, Abhishek332 commented on openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/tier-card.style.less
> +  //   }
done

2023-07-21 07:02 UTC, karanh37 requested changes
The UI is not matching the mocks. I have highlighted few points. Please take care of it.

2023-07-24 10:52 UTC, karanh37 approved these changes
LGTM

2023-07-24 10:53 UTC, karanh37 commented
@harshach - can you review the new Tier changes ?

2023-07-24 11:15 UTC, Ashish8689 approved these changes

2023-07-25 05:36 UTC, harshach approved these changes

2023-07-25 06:04 UTC, merged