Fix #11778: Add support for hive metastore ingestion
open-metadata/OpenMetadata pull request #12599
Opened 2023-07-26 06:37 UTC by ulixius9

### Describe your changes:

Fix #11778: Add support for hive metastore ingestion

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2023-07-27 05:39 UTC, ayush-shah approved these changes

2023-07-27 05:40 UTC, ayush-shah requested changes
We have a potential bug in the code from sonarcloud, and multiple code smells..
can you take a look

2023-07-28 10:55 UTC, ayush-shah approved these changes

2023-07-31 10:24 UTC, chirag-madlani approved these changes

2023-07-31 10:26 UTC, merged