Creating make script for code freeze automation
open-metadata/OpenMetadata pull request #12976
Opened 2023-08-23 12:11 UTC by Anuj359

Adding make module to automate the upgrade process.

test can be reviewed [here](https://github.com/open-metadata/OpenMetadata/compare/main...deuex-solutions:OpenMetadata-1:test/upgrade-code?expand=1)

and to run this we just need to run
`make update_all RELEASE_VERSION=1.2.0 PY_RELEASE_VERSION=1.2.0.0`

2023-08-25 04:52 UTC, akash-jain-10 requested changes

2023-08-25 04:52 UTC, akash-jain-10 commented on Makefile
> +	$(MAKE) update_github_action_paths ; \
Let's remove this from `update_all` make recipe! We will perform this action manually with make recipe call!

2023-08-25 06:05 UTC, OnkarVO7 requested changes

2023-08-29 07:40 UTC, Anuj359 commented on update_version.py
> +    print(f"Updating Github workflow's Docker version in {file_path} to version {release_version}\n")
I have updated the python code with the logger logic, please test it in your local.

You need to clone the repo and switch to my branch.
`git checkout  test/code-freeze`
to run and test this make recipe and python code
 you need to pass env variables while running, you can give any version
`make update_all RELEASE_VERSION=4.4.4 PY_RELEASE_VERSION=4.4.4.4`

let me know with your suggestions if the python code looks good or can be improved? Thanks!

2023-09-04 04:58 UTC, akash-jain-10 submitted a review, later dismissed

2023-09-06 05:55 UTC, OnkarVO7 approved these changes

2023-09-13 09:39 UTC, akash-jain-10 approved these changes

2023-09-13 09:40 UTC, merged