Fixes #12298 - Update report data type to camel case
open-metadata/OpenMetadata pull request #13505
Opened 2023-10-10 08:18 UTC by TeddyCr

### Describe your changes:

Fixes #12298 
- change report data type from pascal to camel case
- implemented migration
- updated docker-compose for Postgres search client

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [x] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

- [x] I have added tests around the new logic.
- [x] For connector/ingestion changes: I updated the documentation.

2023-10-10 08:21 UTC, ayush-shah requested changes

2023-10-10 08:21 UTC, ayush-shah commented on openmetadata-service/src/main/java/org/openmetadata/service/workflows/searchIndex/PaginatedDataInsightSource.java
> +    //    String upperCaseFQN = StringUtils.capitalize(entityFQN);
@TeddyCr looks like the comments came in as part of the commit

2023-10-10 08:36 UTC, pmbrull approved these changes

2023-10-10 08:42 UTC, ayush-shah approved these changes

2023-10-11 06:14 UTC, harshach approved these changes

2023-10-11 06:14 UTC, merged