Feat: Show description on hover of tags
open-metadata/OpenMetadata pull request #1418
Opened 2021-11-27 06:55 UTC by ShaileshParmar11

### Describe your changes :

Show description on hover of tags
Closes #958 
#
### Type of change :

- [x] New feature

#
### Frontend Preview (Screenshots) :
![image](https://user-images.githubusercontent.com/71748675/143671461-7c76d797-6268-4b9a-9f8c-3eeb201636ff.png)
![image](https://user-images.githubusercontent.com/71748675/143671470-ce712785-2358-468c-9006-56452db04b52.png)

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Frontend: @shahsank3t, @darth-coder00, @Sachin-chaurasiya

2021-11-27 08:53 UTC, Sachin-chaurasiya requested changes
@ShaileshParmar11 Tag description is in markdown format so we should Parse markdown text.

2021-11-28 10:44 UTC, mithmatt commented
The "Type: Manual" line - should we consider making this a bit more legible to a user?

"Set by xyz" or "Set manually" or "Set by automation" or "Source: Manually Set"

2021-11-29 07:30 UTC, Sachin-chaurasiya commented
> The "Type: Manual" line - should we consider making this a bit more legible to a user?
> 
> "Set by xyz" or "Set manually" or "Set by automation" or "Source: Manually Set"

@mithmatt Yeah that would be good to provide more context to the user.

2021-11-30 07:53 UTC, Sachin-chaurasiya commented
@ShaileshParmar11 there is one conflict so please resolve it. If you need any help then let us know.

2021-11-30 12:02 UTC, darth-coder00 approved these changes
LGTM!

2021-11-30 12:09 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/components/common/rich-text-editor/RichTextEditorPreviewer.tsx
> +  className,
@ShaileshParmar11 here className is optional so we should give it default value as `className='' `

2021-11-30 12:17 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/components/recently-viewed/RecentlyViewed.tsx
> +              tags: [...tableTags].filter((tag) => tag),
@ShaileshParmar11 We would need a tier in the tag list because tier is also a tag.

2021-11-30 12:25 UTC, Sachin-chaurasiya requested changes
Requested some changes.

2021-11-30 12:26 UTC, Sachin-chaurasiya commented
@ShaileshParmar11 We should not pass tier tags to adding taglist.
![image](https://user-images.githubusercontent.com/59080942/144047137-8d2c4d64-8f2e-49af-b9e9-2976b6f63562.png)

2021-12-01 10:34 UTC, Sachin-chaurasiya approved these changes
LGTM.

2021-12-01 10:35 UTC, merged