fix old password match
open-metadata/OpenMetadata pull request #14273
Opened 2023-12-06 13:15 UTC by harsh-vador

### Describe your changes:

Fixes #12584 

I worked on fixing the old password validation not working while updating new password

#
### Type of change:

- [x] Bug fix

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.

2023-12-11 07:26 UTC, chirag-madlani requested changes

2023-12-11 07:26 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx
> +      }
```suggestion
      const newData = {
        username: userData.name,
        requestType: isLoggedInUser ? RequestType.Self : RequestType.User,
      };

```

2023-12-11 07:26 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx
> +        });
await and then can't be used to gather, We have async await syntax for async operation in the code

2023-12-12 13:42 UTC, harsh-vador commented on openmetadata-ui/src/main/resources/ui/src/components/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx
> +      }
addressed comments

2023-12-13 06:43 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx
> +      }
```suggestion
showErrorToast(error);
```

2023-12-13 06:49 UTC, harsh-vador commented on openmetadata-ui/src/main/resources/ui/src/components/Users/UsersProfile/UserProfileDetails/UserProfileDetails.component.tsx
> +      }
addressed

2023-12-13 08:49 UTC, chirag-madlani approved these changes

2023-12-13 08:56 UTC, 07Himank approved these changes

2023-12-13 09:02 UTC, merged