Fix 13823: Validate and Parse gracefully IngestionPipeline
open-metadata/OpenMetadata pull request #14461
Opened 2023-12-20 14:19 UTC by OnkarVO7

### Describe your changes:

Fixes https://github.com/open-metadata/OpenMetadata/issues/13823

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2023-12-20 15:08 UTC, pmbrull requested changes

2023-12-20 15:08 UTC, pmbrull commented on ingestion/src/metadata/ingestion/api/parser.py
> +    except ValidationError:
should we take care of the `serviceConnection`? Not only the `sourceConfig`

2023-12-20 15:08 UTC, pmbrull commented on ingestion/src/metadata/ingestion/api/parser.py
> +    except ValidationError:
I believe that's where we get also a lot of noise, for example when we configure an URI without the scheme or something

2023-12-21 08:58 UTC, pmbrull commented on ingestion/src/metadata/ingestion/api/parser.py
> +    except ValidationError:
as discussed, that was the wrong comment. We'll be adding it to the run_automations endpoint though

2023-12-21 15:59 UTC, OnkarVO7 commented on ingestion/src/metadata/ingestion/api/parser.py
> -def parse_test_connection_request_gracefully(
Removing the method since it wasn't being used anywhere except for tests.

2023-12-21 16:02 UTC, pmbrull approved these changes

2023-12-22 04:26 UTC, merged