migrated all usages of models.MetadataUser & models.User classes to g…
open-metadata/OpenMetadata pull request #1448
Opened 2021-11-28 22:30 UTC by omriAl

…enerated.schema.teams.user.User classes instead.

### Describe your changes :
migrated all usages of models.MetadataUser & models.User classes to generated.schema.teams.user.User classes instead. I This was in order to use only the native pydantic generated models.

#
### Type of change :

- [] Bug fix
- [x] Improvement
- [] New feature
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

@amiorin @pmbrull 
### Reviewers

2021-11-28 22:31 UTC, harshach commented
Thanks for taking this up @omriAl

2021-11-28 22:32 UTC, harshach approved these changes

2021-11-28 22:40 UTC, harshach commented
@omriAl looks like check style is breaking.
```
make install_dev
make precommit_install
```

re-commit these changes in your branch so that isort and black can run and it will fix these issues

2021-11-29 06:04 UTC, mithmatt commented on ingestion/tests/integration/ldap/test_ldap_crud.py
> +# from metadata.ingestion.models.user import MetadataUser, User
Remove this commented out import?

2021-11-29 07:06 UTC, pmbrull commented
> @omriAl looks like check style is breaking.
> 
> ```
> make install_dev
> make precommit_install
> ```
> 
> re-commit these changes in your branch so that isort and black can run and it will fix these issues

Thanks, @omriAl for tackling this! The docs on the `ingestion` setup have not yet been published to the gitbook so that is why you might have missed them, sorry for that.

As @harshach says, installing the recommit hooks will take care of formatting code & imports while you develop, as well as running `flake8` to pick up linting issues early on.

Another option is to directly call `make isort black`, which will run the tools on demand.

Hope this helps!

2021-11-29 10:26 UTC, amiorin commented
@harshach 
Is it safe to merge this PR?
![image](https://user-images.githubusercontent.com/32617/143851211-20d38ac6-a5f6-446d-a4d9-3b6f6c2bee47.png)

2021-11-29 23:22 UTC, harshach requested changes
@omriAl looks like you included the commits that shouldn't be in this PR. Please checkout a new branch and cherry-pick the changes you made and create a new PR.

2021-11-30 07:11 UTC, omriAl commented
@harshach yes, my bad, my main branch on the fork was behind.
created a new one:
https://github.com/open-metadata/OpenMetadata/pull/1473

2022-03-02 03:06 UTC, mithmatt commented
Closing out of date PR, actual changes covered in #1473

2022-03-02 03:06 UTC, closed without merging