Update cypress workflows
open-metadata/OpenMetadata pull request #14513
Opened 2023-12-28 06:47 UTC by preetsshah

### Describe your changes:

Fixes [#14483](https://github.com/open-metadata/OpenMetadata/issues/14483)

Since Cypress project ID for workflows triggered by PRs and schedule (including workflow dispatch) should be different, Introduced a new step in the CI workflows `cypress-integration-tests-mysql.yml` and `cypress-integration-tests-postgresql.yml` that would check the type of event and set a new environment variable `PROJECT_ID` which would be passed to `Run Cypress Tests` step.

Also removed scheduled event triggers from the skip workflows as it is not required.

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-01-03 09:26 UTC, akash-jain-10 requested changes

2024-01-03 09:48 UTC, akash-jain-10 approved these changes

2024-01-03 12:07 UTC, akash-jain-10 requested changes

2024-01-03 12:07 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql.yml
> +          fi
```suggestion
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "PROJECT_ID=${{ secrets.CYPRESS_SCHEDULE_PROJECT_ID }}" >> $GITHUB_OUTPUT
          else
            echo "PROJECT_ID=${{ secrets.CYPRESS_PR_PROJECT_ID }}" >> $GITHUB_OUTPUT
          fi
```

2024-01-03 12:09 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-postgresql.yml
> +
```suggestion
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "PROJECT_ID=${{ secrets.CYPRESS_SCHEDULE_PROJECT_ID }}" >> $GITHUB_OUTPUT
          else
            echo "PROJECT_ID=${{ secrets.CYPRESS_PR_PROJECT_ID }}" >> $GITHUB_OUTPUT
          fi

```

2024-01-04 05:28 UTC, akash-jain-10 approved these changes

2024-01-04 05:28 UTC, chirag-madlani approved these changes

2024-01-04 13:34 UTC, merged