Feat: added tour guide for user
open-metadata/OpenMetadata pull request #1463
Opened 2021-11-29 14:14 UTC by ShaileshParmar11

### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

Frontend: @shahsank3t, @darth-coder00, @Sachin-chaurasiya

2021-12-08 17:42 UTC, harshach commented
@ShaileshParmar11 this looks great!! awesome job
but our front page is changed :) 
cc @shahsank3t @Sachin-chaurasiya

2021-12-08 17:52 UTC, shahsank3t commented
@harshach Yes, that's the reason this PR is in draft. Once new changes are properly implemented, Shailesh can continue on this again on the new one.

2021-12-09 04:16 UTC, ShaileshParmar11 commented
> @ShaileshParmar11 this looks great!! awesome job but our front page is changed :) cc @shahsank3t @Sachin-chaurasiya

Thank you..! and yes as soon as the new design is implemented ill make the necessary changes for this feature.

2021-12-22 09:58 UTC, darth-coder00 requested changes
Added few comments

2021-12-22 09:58 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/package.json
> +    "@deuex-solutions/react-tutorial": "1.0.0"
Move it up with redoc package

2021-12-22 09:58 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
> +              location.pathname.includes(ROUTES.TOUR) ? false : isEntityLoading
```suggestion
              !location.pathname.includes(ROUTES.TOUR) && isEntityLoading
```

2021-12-22 09:58 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/src/components/app-bar/Appbar.tsx
> +                      appState.currentTourPage = 'explorePage';
Should have `enum` for Tour pages

2021-12-22 09:58 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/src/components/MyDataHeader/MyDataHeader.component.tsx
> +  const { users, userTeams, isTourOpen } = AppState;
Discard changes for this file

2021-12-22 09:58 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx
> +      AppState.currentTourPage = 'datasetPage';
Same here

2021-12-22 09:58 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/src/react-app-env.d.ts
>  declare module 'react-tutorial';
Remove this now

2021-12-22 10:04 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/package.json
> +    "@deuex-solutions/react-tutorial": "1.0.0"
Done

2021-12-22 10:06 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/Explore/Explore.component.tsx
> +              location.pathname.includes(ROUTES.TOUR) ? false : isEntityLoading
updated

2021-12-22 11:00 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/app-bar/Appbar.tsx
> +                      appState.currentTourPage = 'explorePage';
updated

2021-12-22 11:10 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/MyDataHeader/MyDataHeader.component.tsx
> +  const { users, userTeams, isTourOpen } = AppState;
updated

2021-12-22 11:11 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/common/table-data-card/TableDataCard.tsx
> +      AppState.currentTourPage = 'datasetPage';
updated

2021-12-22 12:56 UTC, darth-coder00 approved these changes
LGTM!

2021-12-22 14:26 UTC, merged