add workflow for cypress pr integration
open-metadata/OpenMetadata pull request #15290
Opened 2024-02-21 11:33 UTC by harsh-vador

### Describe your changes:

I worked on adding a workflow for cypress PR integration that will help run a particular cypress based on PR labels.

#
### Type of change:

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-02-21 11:48 UTC, chirag-madlani commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +               && contains(github.event.pull_request.labels.*.name, 'e2e')
Let's remove e2e condition from here
```suggestion
               
```

2024-02-21 11:48 UTC, chirag-madlani commented on .github/workflows/cypress-integration-tests-postgresql-pr.yml
Let's not add Postgres, Just MySQL will be fine

2024-02-21 12:07 UTC, chirag-madlani submitted a review, later dismissed

2024-02-22 05:54 UTC, akash-jain-10 requested changes

2024-02-22 05:54 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +    - cron: "30 2 * * 1,3,5"
Let's remove this!
```suggestion
 
```

2024-02-22 05:54 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +  group: cypress-integration-tests-mysql-${{ github.head_ref || github.run_id }}
```suggestion
  group: cypress-integration-tests-pr-mysql-${{ github.head_ref || github.run_id }}
```

2024-02-22 05:54 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +             )
```suggestion
      github.event_name == 'workflow_dispatch'
          || ( github.event_name == 'pull_request_target'
               && github.event.pull_request.draft == false
             )
```

2024-02-22 05:54 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +          fi
```suggestion
          echo "CYPRESS_PROJECT_ID=${{ secrets.CYPRESS_PR_PROJECT_ID }}" >> $GITHUB_OUTPUT
           echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_PR_RECORD_KEY }}" >> $GITHUB_OUTPUT
```

2024-02-22 05:54 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +          group: cypress-ci-psql-oss-${{ github.run_id }}-${{github.run_attempt}}
```suggestion
          group: cypress-ci-mysql-pr-oss-${{ github.run_id }}-${{github.run_attempt}}
```

2024-02-22 05:54 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +          GREP_TAGS: "${{ steps.get_cypress_filter.outputs.FILTER }}"
This should not be required anymore!

2024-02-22 06:09 UTC, akash-jain-10 commented on .github/workflows/cypress-integration-tests-mysql-pr.yml
> +          GREP_TAGS: "${{ steps.get_cypress_filter.outputs.FILTER }}"
This is not required anymore. Let's clean it up!

2024-02-22 06:27 UTC, akash-jain-10 approved these changes

2024-02-22 09:18 UTC, merged