Fix #15062 & #14810: Fix Column level lineage overwrites pipeline Lineage & manual col lineage
open-metadata/OpenMetadata pull request #15897
Opened 2024-04-15 10:09 UTC by ulixius9

### Describe your changes:

Fix #15062 & Fix #14810: Fix Column level lineage overwrites pipeline Lineage & manual col lineage

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-04-18 13:14 UTC, sushi30 requested changes
I suggest adding a test case or a video demonstrating the fix

2024-04-18 14:18 UTC, pmbrull commented
> I suggest adding a test case or a video demonstrating the fix

+1 on getting the backend covered 🙏

2024-04-22 13:44 UTC, mohityadav766 approved these changes

2024-04-22 13:50 UTC, sushi30 approved these changes

2024-04-23 04:07 UTC, merged