Activity feed card fixes
open-metadata/OpenMetadata pull request #16166
Opened 2024-05-08 06:38 UTC by Ashish8689

### Describe your changes:

- I worked on Activity feed card fixes

Issue : 

<img width="992" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/c5d638fc-7b22-4a88-9375-bce5b7e7abe8">
<img width="637" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/1d6bf632-7ee9-4885-8e06-05c2ea75dd85">
<img width="1039" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/c1d5925d-45a7-4e39-95ea-593acd1b6505">
<img width="300" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/c42364de-3e8b-4cc2-8228-2eff0ee7a87c">
<img width="1029" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/2af76c3e-1dbe-4ea1-b116-a4009461213f">
<img width="142" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/dab60fb0-1d68-4ddb-b232-0fc2bd3fb7a4">

Resolved : 
<img width="992" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/6eebbcf7-2081-4d03-b930-d1d01d8fea2b">

<img width="637" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/8d2037ad-ecaf-4454-80aa-679686599f8e">

<img width="1039" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/5fcb0aad-d576-4921-9eb4-5bbd54dbf397">
<img width="394" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/99ab5960-9e5e-4f32-9353-ac611befb6be">

<img width="1029" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/b7d6cc49-7424-4cf0-a00f-58fc1cf20c46">

<img width="1029" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/8c2e2881-7d69-4691-9dd0-89e7f439259f">

<img width="142" alt="image" src="https://github.com/open-metadata/OpenMetadata/assets/66266464/a96f0bb3-bd12-41dc-a14a-7bebdb16aac4">

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-05-08 13:47 UTC, mohityadav766 approved these changes

2024-05-08 14:07 UTC, karanh37 requested changes
Pls add unit tests everywhere.

2024-05-09 05:23 UTC, Ashish8689 commented on openmetadata-ui/src/main/resources/ui/src/utils/CommonUtils.tsx
> +    return splitFqn.splice(-1).join(FQN_SEPARATOR_CHAR);
so this is two different thing, here we are getting the `testSuite` name which is in last and from `getTestSuiteFQN ` we are getting the FQN for it without the `testSuite` name.

2024-05-09 13:07 UTC, karanh37 approved these changes

2024-05-10 05:24 UTC, mohityadav766 approved these changes

2024-05-10 05:30 UTC, chirag-madlani approved these changes

2024-05-10 05:34 UTC, merged