Fixes 16305: Added Test Case for Matching Enum
open-metadata/OpenMetadata pull request #16362
Opened 2024-05-21 10:00 UTC by sushi30

fixes https://github.com/open-metadata/OpenMetadata/issues/16305

1. Implemented the test case using the `matchEnum` parameter.
2. Added integration tests.
3. Added migrations.

### Describe your changes:

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-05-21 12:23 UTC, TeddyCr requested changes
@sushi30 I believe we need to keep the schema files from the doc (or update them if we need to) they are part of this section https://docs.open-metadata.org/v1.3.x/main-concepts/metadata-standard/schemas

2024-05-21 12:26 UTC, sushi30 commented
@TeddyCr The schema docs are regenerated only for schema json files. Test definitions are defined in as `data` resources and therefore dont generate schema documentations.

They are instead documented here:
https://docs.open-metadata.org/v1.3.x/connectors/ingestion/workflows/data-quality/tests

2024-05-22 14:58 UTC, TeddyCr approved these changes

2024-05-23 15:44 UTC, TeddyCr approved these changes

2024-05-24 13:29 UTC, TeddyCr approved these changes

2024-05-27 15:37 UTC, sushi30 commented
@TeddyCr this is finally passing.. moved migrations to `1.5`

2024-05-28 06:12 UTC, TeddyCr approved these changes

2024-05-28 07:30 UTC, merged