Fix #14676: Athena S3 Lineage
open-metadata/OpenMetadata pull request #16426
Opened 2024-05-27 11:48 UTC by harshsoni2024

### Describe your changes:

Fixes #14676 

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-05-28 13:06 UTC, sushi30 requested changes
lets add a test case for this

2024-05-28 13:09 UTC, sushi30 commented
we can use [localstack athena](https://docs.localstack.cloud/user-guide/aws/athena/) similar to the way [dynamo db is tested](https://github.com/open-metadata/OpenMetadata/blob/7dad49640d326e595c927f0cbd3b44636ffec1bf/ingestion/tests/integration/profiler/test_dynamodb.py).

2024-06-06 09:29 UTC, harshsoni2024 commented
> we can use [localstack athena](https://docs.localstack.cloud/user-guide/aws/athena/) similar to the way [dynamo db is tested](https://github.com/open-metadata/OpenMetadata/blob/7dad49640d326e595c927f0cbd3b44636ffec1bf/ingestion/tests/integration/profiler/test_dynamodb.py).

@sushi30 , I had checked the working of mocking athena with localstack and testcontainers. I found out that athena db operations comes under pro account/image. [link](https://docs.localstack.cloud/references/coverage/coverage_athena/)

2024-06-24 14:30 UTC, sushi30 commented on ingestion/src/metadata/ingestion/source/database/athena/utils.py
> +# @reflection.cache
why is there a comment here?

2024-06-24 14:35 UTC, sushi30 commented on ingestion/tests/unit/topology/database/test_athena.py
> +                arrayDataType=None,
I suggest removing all the `None` fields to make the file more concise. This also allows changing the models without needing to change the test files.

2024-06-26 13:20 UTC, harshsoni2024 commented on ingestion/src/metadata/ingestion/source/database/athena/utils.py
> +# @reflection.cache
I think it was on wrong place.

2024-06-26 13:30 UTC, sushi30 approved these changes

2024-06-26 14:23 UTC, merged