MINOR: Pydantic fixes for redshift & kafka
open-metadata/OpenMetadata pull request #16638
Opened 2024-06-12 19:41 UTC by ulixius9

### Describe your changes:

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-06-13 09:42 UTC, sushi30 requested changes
1. it appears airflow api tests are failing after the change
2. what was the error with kafka? is it possible to create a regression test for this?

2024-06-13 14:48 UTC, ulixius9 commented
@sushi30 I've included tests and the airflow tests are actually not failing this is a know issue which is yet to be fixed, if you check the logs all tests actually passed

2024-06-13 14:49 UTC, sushi30 approved these changes

2024-06-13 14:50 UTC, sushi30 requested changes
great. since this is an integration test can you move it there?

2024-06-14 08:37 UTC, OnkarVO7 approved these changes

2024-06-14 08:38 UTC, sushi30 approved these changes

2024-06-14 08:38 UTC, merged