MINOR: Fix Oracle E2E Tests
open-metadata/OpenMetadata pull request #17084
Opened 2024-07-18 16:05 UTC by IceS2

Fixes Oracle E2E Tests

Profiler test is broken due to a bug. We don't seem to support Oracle Blob Type. An issue will be open to fix this and remove the expected failure.

```
sqlalchemy.exc.DatabaseError: (oracledb.exceptions.DatabaseError) ORA-00932: inconsistent datatypes: expected - got BLOB
Help: https://docs.oracle.com/error-help/db/ora-00932/
[SQL: /* {"app": "***", "version": "1.5.0.0.***0"} */
SELECT anon_2.anon_1, anon_2."valuesCount", anon_2."distinctCount", anon_2.anon_1 AS anon_1_1, anon_2.anon_1 AS anon_1_2, anon_2."nullCount", anon_2.anon_1 AS anon_1_3, anon_2.anon_1 AS anon_1_4 
FROM (SELECT NULL AS anon_1, count(photo) AS "valuesCount", count(DISTINCT photo) AS "distinctCount", NULL AS anon__1, NULL AS anon__2, SUM(CAST(CASE WHEN (photo IS NULL) THEN :param_1 ELSE :param_2 END AS NUMBER)) AS "nullCount", NULL AS anon__3, NULL AS anon__4 
FROM ***.***_emp_view) anon_2 
WHERE ROWNUM <= 1]
[parameters: {'param_1': 1, 'param_2': 0}]
```

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-07-18 16:17 UTC, sushi30 requested changes

2024-07-18 16:17 UTC, sushi30 commented on ingestion/tests/cli_e2e/test_cli_oracle.py
> +    @pytest.mark.xfail
add the the link to the issue in the reason

2024-07-18 16:19 UTC, sushi30 commented on ingestion/tests/cli_e2e/test_cli_oracle.py
> +    @pytest.mark.xfail
example: https://github.com/open-metadata/OpenMetadata/blob/a455bbe0ce08fe7f015754b64ac70d17e125cd32/ingestion/tests/integration/postgres/test_usage.py#L51

2024-07-18 16:24 UTC, sushi30 submitted a review, later dismissed

2024-07-19 08:32 UTC, pmbrull approved these changes

2024-07-19 08:32 UTC, merged