[GEN-1069] - Fix dbt issues in ingestion
open-metadata/OpenMetadata pull request #17247
Opened 2024-07-31 14:10 UTC by TeddyCr

### Describe your changes:
- Fix test case creation by limiting it only if it does not already exists
- Increase `name` VARCHAR length 

#
### Type of change:

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] My PR title is `Fixes <issue-number>: <short explanation>`
- [x] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

Bug fix
- [x] I have added a test that covers the exact scenario we are fixing. For complex issues, comment the issue number in the test for future reference.

2024-07-31 14:12 UTC, pmbrull submitted a review, later dismissed

2024-07-31 14:16 UTC, OnkarVO7 requested changes

2024-07-31 14:16 UTC, OnkarVO7 commented on ingestion/src/metadata/ingestion/source/database/dbt/metadata.py
> +                    test_case_fqn = f"{get_table_or_column_fqn(entity_link_str)}.{manifest_node.name}"
To build the fqn might be better to use the fqn builder

2024-07-31 14:49 UTC, OnkarVO7 submitted a review, later dismissed

2024-07-31 15:03 UTC, pmbrull submitted a review, later dismissed

2024-08-01 13:50 UTC, OnkarVO7 approved these changes

2024-08-02 07:10 UTC, OnkarVO7 approved these changes

2024-08-02 10:29 UTC, merged