minor: disable image upload support in description editor
open-metadata/OpenMetadata pull request #17697
Opened 2024-09-04 08:34 UTC by Sachin-chaurasiya

**Before**

https://github.com/user-attachments/assets/6049bc7c-063d-48c4-aa2e-dc3e0df23ab7

**After**

https://github.com/user-attachments/assets/c7ead0b3-f2c5-4d90-ae95-1edf71047e81

2024-09-04 11:20 UTC, chirag-madlani submitted a review, later dismissed

2024-09-04 12:20 UTC, pmbrull requested changes

2024-09-04 12:20 UTC, pmbrull commented on openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
> +    "image-upload-error": "Image upload is not supported",
```suggestion
    "image-upload-error": "Image upload is not supported. Please use Markdown syntax for images available via URL.",
```

Or something like that? We should do this everywhere

2024-09-04 14:39 UTC, pmbrull approved these changes

2024-09-05 07:00 UTC, chirag-madlani approved these changes

2024-09-05 07:40 UTC, merged