change replaced dict by model_dump
open-metadata/OpenMetadata pull request #18108
Opened 2024-10-03 18:53 UTC by kuma0128

### Describe your changes:

Fixes https://github.com/open-metadata/OpenMetadata/issues/18104

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-10-04 05:09 UTC, kuma0128 commented
@pmbrull 
hi could you attach "safe to test" tag ?

2024-10-11 13:13 UTC, TeddyCr commented on ingestion/src/metadata/ingestion/source/database/databricks/metadata.py
> -                rows = dict(
@kuma0128 I don't think we need to replace these once. this is python native `dict` and not pydantic `dict`. The pydantic `dict` would be something like `PydanticModel.dict()`

2024-10-11 13:13 UTC, TeddyCr requested changes
@kuma0128 we just need to replace the dict method of a Pydantic model not the python native dict

2024-10-14 12:50 UTC, sushi30 commented
@kuma0128 please update the branch to pull fixes to looker sdk

2024-11-20 09:47 UTC, sushi30 commented
There is no built-in method `model_dump`. Please follow ([issue appears to be specific with Athena](https://github.com/144b4572302480bba641cd2cb7cbd28c?pvs=25#144b4572302480998370ff22317bc4d6)) to fix this issue.

2024-11-20 09:48 UTC, sushi30 requested changes
There is no built-in method `model_dump`. Please follow ([issue appears to be specific with Athena](https://github.com/144b4572302480bba641cd2cb7cbd28c?pvs=25#144b4572302480998370ff22317bc4d6)) to fix this issue.

2025-03-05 09:44 UTC, closed without merging