Feat persona table page
open-metadata/OpenMetadata pull request #18550
Opened 2024-11-07 18:59 UTC by chirag-madlani

### Describe your changes:

Fixes <issue-number>

I worked on ... because ...

#
### Type of change:

- [ ] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2025-02-24 12:09 UTC, karanh37 requested changes

2025-02-24 12:57 UTC, aniketkatkar97 commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +          ]}
Why are we passing hard-coded tags list?

2025-02-24 12:57 UTC, aniketkatkar97 commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +            },
Same here

2025-02-24 12:57 UTC, aniketkatkar97 commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +            },
Same here

2025-02-24 12:57 UTC, aniketkatkar97 commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +          ]}
Same here

2025-02-24 12:57 UTC, aniketkatkar97 commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +              />
We should use Button for assigning onClick

2025-02-24 12:57 UTC, aniketkatkar97 commented on openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardDetails/DashboardDetails.component.tsx
> +
In case of failure, we are not setting the customizedPage and by default it's null. should there be a fallback layout in such cases?

2025-02-24 12:57 UTC, aniketkatkar97 commented on openmetadata-ui/src/main/resources/ui/src/components/Entity/EntityRightPanel/EntityRightPanel.tsx
> +        <PartitionedKeys />
Are knowledge articles and customPropertyTables, not widgets?

2025-02-24 19:43 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/playwright/support/entity/ingestion/ServiceBaseClass.ts
> -
Put back individual widget check since we removed EntityRightPanel

2025-02-24 19:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/utils/APICollection/APICollectionClassBase.ts
> +      href: 'http://sandbox-beta.open-metadata.org/api/v1/apiCollections/db03ef8f-82f9-4a23-a940-3ba5af5bba29',
Yes here: https://github.com/open-metadata/OpenMetadata/blob/ee5f4f5b17bf1c3345ef28be79eae0f2b923f092/openmetadata-ui/src/main/resources/ui/src/utils/CustomizePage/CustomizePageUtils.ts#L336

2025-02-24 19:49 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Dashboard/DashboardDetails/DashboardDetails.component.tsx
> +
Yes fallback layout is present for all the base classes. i.e. here: https://github.com/open-metadata/OpenMetadata/blob/ee5f4f5b17bf1c3345ef28be79eae0f2b923f092/openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericTab/GenericTab.tsx#L36

2025-02-24 19:54 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/CustomizeTableDetailPage/CustomizeTableDetailPage.tsx
> +
Not expected to render for any other type. I added it initially when I started with a few pages. Let me think of something nice here as error handling

2025-02-24 19:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +          ]}
It will be seen at the time of customization, unlike the landing page, we don't have any API to populate data here, so we need to hardcode it

2025-02-24 19:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +            },
same

2025-02-24 19:57 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Customization/GenericWidget/GenericWidget.tsx
> +            },
same

2025-02-25 12:17 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/utils/DatabaseSchemaClassBase.ts
> +        },
will do it in next iteration

2025-02-26 10:23 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/utils/TableClassBase.ts
> +    }));
will do that next

2025-02-26 12:48 UTC, aniketkatkar97 approved these changes

2025-02-26 12:59 UTC, Ashish8689 submitted a review, later dismissed

2025-02-27 06:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Tag/TagsContainerV2/TagsContainerV2.tsx
> +                  {conversationThreadElement}
Validated, working as expected

2025-02-27 06:52 UTC, karanh37 approved these changes

2025-02-27 10:13 UTC, merged