feat: Docs for openmetadata post upgrade steps with kubernetes.
open-metadata/OpenMetadata pull request #18972
Opened 2024-12-09 11:52 UTC by tarunpandey23

### Describe your changes:

Fixes <issue-number>

I worked on ... because, to  implement CronJobs for reindexing and the deploy pipeline using the Kubernetes CLI. While these tasks can be performed via the UI as part of the Post-Upgrade Steps, this approach provides an alternative for users who prefer or require command-line operations. 
here I updated the documentation for the issue in openmetadata-helm-chart repository (https://github.com/open-metadata/openmetadata-helm-charts/issues/287#issuecomment-2527672270) to include detailed instructions for these Kubernetes-based solutions.

<img width="1794" alt="Screenshot 2024-12-11 at 2 32 42 PM" src="https://github.com/user-attachments/assets/bcb73683-1bd8-4e14-9f18-b71edc26b844">
<img width="1792" alt="Screenshot 2024-12-11 at 2 32 57 PM" src="https://github.com/user-attachments/assets/16279eb6-d870-47ad-b557-9836e95e8822">

#
### Type of change:

- [ ] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] My PR title is `Fixes <issue-number>: <short explanation>`
- [ ] I have commented on my code, particularly in hard-to-understand areas. 
- [ ] For JSON Schema changes: I updated the migration scripts or explained why it is not needed.

2024-12-11 09:04 UTC, tarunpandey23 commented
<img width="1794" alt="Screenshot 2024-12-11 at 2 32 42 PM" src="https://github.com/user-attachments/assets/3c3197ae-0fb4-44bb-88d5-36dc09b38eb3">
<img width="1792" alt="Screenshot 2024-12-11 at 2 32 57 PM" src="https://github.com/user-attachments/assets/253e6205-5577-4f77-b3cc-ab6d92af66d4">


Here is the screenshots attached, which describes how the changes will look in UI openmetadata docs.

2024-12-12 05:47 UTC, Prajwal214 requested changes
@tarunpandey23 Can you add the same content in v1.7 docs as well.

2024-12-12 07:06 UTC, akash-jain-10 approved these changes

2024-12-12 07:13 UTC, Prajwal214 approved these changes

2024-12-12 07:21 UTC, merged