added selenium tests for tags with space
open-metadata/OpenMetadata pull request #2129
Opened 2022-01-10 08:14 UTC by parthp2107

### Describe your changes :

Added selenium tests for tags name with spaces

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

2022-01-10 14:42 UTC, shahsank3t requested changes

2022-01-11 06:22 UTC, parthp2107 commented on openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/pages/common/CommonTests.java
> +    URL url = new URL("http://localhost:8585/api/v1/tags/" + tagCategoryDisplayName + "/");
Addressed in the latest commit.

2022-01-11 06:22 UTC, parthp2107 commented on openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/pages/common/CommonTests.java
> +    URL url = new URL("http://localhost:8585/api/v1/tags/");
Addressed in the latest commit.

2022-01-11 11:14 UTC, shahsank3t approved these changes

2022-01-11 12:15 UTC, merged