issue-211: added addtional inforamtion related to driver class, frequ…
open-metadata/OpenMetadata pull request #235
Opened 2021-08-19 13:34 UTC by ShaileshParmar-WebDeveloper

…ency and service type

### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
![image](https://user-images.githubusercontent.com/71748675/130077102-bc25d8f9-a1a1-47a5-aede-5ffdb48b3333.png)
![image](https://user-images.githubusercontent.com/71748675/130077201-999db102-797e-4af5-87d9-c55d7bd560f2.png)

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2021-08-20 08:35 UTC, shahsank3t approved these changes
+1 LGTM
@darth-coder00 please review this once.

2021-08-20 08:39 UTC, Sachin-chaurasiya requested changes

2021-08-20 08:39 UTC, Sachin-chaurasiya commented on catalog-rest-service/src/main/resources/ui/src/components/searched-data/SearchedData.tsx
>                          <Pagination
We have a constant page size. so you can use it here instead of 10.

2021-08-20 08:50 UTC, Sachin-chaurasiya approved these changes

2021-08-23 05:02 UTC, darth-coder00 approved these changes
LGTM

2021-08-23 05:03 UTC, merged