added sorting on explore page
open-metadata/OpenMetadata pull request #279
Opened 2021-08-23 13:48 UTC by Sachin-chaurasiya

Closes #123 
### Describe your changes :

I worked on the Explore page to add sorting and ordering.

#
### Type of change :

- [x] New feature

#
### Frontend Preview (Screenshots) :
![image](https://user-images.githubusercontent.com/59080942/130458202-8722976a-c7c3-441e-820b-6e16e818892b.png)

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

2021-08-23 15:28 UTC, shahsank3t requested changes
@Sachin-chaurasiya these sorting options needs to be right-aligned as we are going to have entity tabs (Table, Topics, Metrics, etc) that will be left aligned

2021-08-23 16:09 UTC, Sachin-chaurasiya commented
![image](https://user-images.githubusercontent.com/59080942/130480711-c048bcad-f6e3-4232-9bea-0b9c21d6b389.png)

2021-08-23 16:31 UTC, shahsank3t requested changes

2021-08-23 16:31 UTC, shahsank3t commented on catalog-rest-service/src/main/resources/ui/src/constants/constants.ts
> +  { name: 'Weekly_stats', value: 'weekly_stats' },
Name should not be key, instead should be human-readable text.
`Weekly Stats`, `Daily Stats`, `Monthly Stats` and `Last Updated Timestamp`

2021-08-24 04:09 UTC, shahsank3t approved these changes

2021-08-24 04:09 UTC, merged