Fix #3046 UI Add support for request description
open-metadata/OpenMetadata pull request #3074
Opened 2022-03-02 11:01 UTC by Sachin-chaurasiya

Closes #3046 
### Describe your changes :

I worked on issue #3046.

#
### Type of change :

- [x] New feature

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00

2022-03-02 19:42 UTC, vivekratnavel requested changes
Overall looks good to me. I have added inline comments/suggestions to improve.

2022-03-02 19:42 UTC, vivekratnavel commented on openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
> +          body: 'Thread is created successfully',
```suggestion
          body: 'Conversation created successfully',
```

2022-03-02 19:42 UTC, vivekratnavel commented on openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
> +          body: 'Error while creating thread',
```suggestion
          body: 'Error while creating the conversation',
```

2022-03-02 19:42 UTC, vivekratnavel commented on openmetadata-ui/src/main/resources/ui/src/utils/FeedElementUtils.tsx
> +    return;
If the owner is not defined, can we have the message without the mention? The users will then have an option to tag a user with the message.

2022-03-03 07:50 UTC, Sachin-chaurasiya commented
@vivekratnavel, Thank you for the review. I'll look into it.

2022-03-03 18:36 UTC, vivekratnavel commented on openmetadata-ui/src/main/resources/ui/src/components/ActivityFeed/ActivityFeedEditor/ActivityFeedEditor.tsx
> +              'tw-py-0.5 tw-px-1 tw-rounde tw-bg-none',
tw-rounded?
```suggestion
              'tw-py-0.5 tw-px-1 tw-rounded tw-bg-none',
```

2022-03-03 19:04 UTC, vivekratnavel commented
- This placeholder looks good. One minor improvement could be to include the actual icon in the place of "chat icon" text.

<img width="1043" alt="Screen Shot 2022-03-03 at 10 36 21 AM" src="https://user-images.githubusercontent.com/1051198/156630085-f184b705-0326-4030-ba3b-b4ea433831d6.png">
Something like this
<img width="568" alt="Screen Shot 2022-03-03 at 10 42 03 AM" src="https://user-images.githubusercontent.com/1051198/156631128-cf5bb01e-0fd8-4b7f-94fe-68c42ac7d67a.png">

- The "Start new conversation" icon renders with different sizes and the position of (+) is not consistent.
<img width="732" alt="Screen Shot 2022-03-03 at 10 34 45 AM" src="https://user-images.githubusercontent.com/1051198/156630094-a388dfd6-115b-4fa8-9bf0-6ff9f9ead0bc.png">

- Also, the start conversation icon should only be shown on hover just like the edit icon. The tags column should also show this icon on hover to start a new conversation around tags.
- The request description text here should be a button to improve UX. Here it matches with the same color as the disabled "No description added" text and doesn't look like an action item that the user can click on. Also, in my opinion, the text can be "No description"
<img width="345" alt="Screen Shot 2022-03-03 at 10 46 53 AM" src="https://user-images.githubusercontent.com/1051198/156631765-5a9ca6cd-de21-4302-a488-efd31a4d5e54.png">
It can even be as subtle as this not to grab attention but be present everywhere. The button can brighten up on hover with a different border color (primary)
<img width="267" alt="Screen Shot 2022-03-03 at 11 00 25 AM" src="https://user-images.githubusercontent.com/1051198/156633998-4074d9d9-a5d6-4130-993d-c67f2de0866b.png">

2022-03-03 19:04 UTC, vivekratnavel commented on openmetadata-ui/src/main/resources/ui/src/utils/FeedUtils.ts
>    if (count === 0) return 'Reply in thread';
```suggestion
  if (count === 0) return 'Reply in conversation';
```

2022-03-04 15:12 UTC, darth-coder00 requested changes
One minor comment, otherwise LGTM!

2022-03-04 15:12 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/src/utils/SvgUtils.tsx
> +import IconCommentPlus from '../assets/svg/add-chat01.svg';
Use better SVG names instead of adding numbers

2022-03-04 15:36 UTC, darth-coder00 approved these changes
LGTM!

2022-03-04 19:23 UTC, vivekratnavel commented
Selenium tests are failing and some of them might be related to the changes in this patch:
```
2022-03-04T19:11:30.4443127Z [ERROR] Failures: 
2022-03-04T19:11:30.4454436Z [ERROR]   CommonTests.addMultipleTagsCheck:196 expected [11] but found [0]
2022-03-04T19:11:30.4454848Z [ERROR]   CommonTests.searchNotShowingResultsCheck:409 No search results found
2022-03-04T19:11:30.4456594Z [ERROR]   DashboardDetailsPageTest.editChartDescription:180 Description not updated
2022-03-04T19:11:30.4458326Z [ERROR]   DashboardServiceTestPage.checkConnectionConfigTab:137 Error while updating service
2022-03-04T19:11:30.4460066Z [ERROR]   DatabaseServicePageTest.checkConnectionConfigTab:159 Error while updating service
2022-03-04T19:11:30.4461845Z [ERROR]   MyDataPageTest.checkRecentlyViewed:274 expected [dim_address] but found [shopify]
2022-03-04T19:11:30.4462772Z [ERROR]   PipelineDetailsPageTest.editTaskDescription:187 Description not updated
2022-03-04T19:11:30.4463292Z [ERROR]   RolesPageTest.addRole:90 Role not added
2022-03-04T19:11:30.4464027Z [ERROR]   RolesPageTest.addRuleWithoutOperation:222->addRole:90 Role not added
2022-03-04T19:11:30.4464530Z [ERROR]   TagsPageTest.addTagWithExistingName:231 expected [Not Used] but found [1]
2022-03-04T19:11:30.4465066Z [ERROR]   TeamsPageTest.addAsset:166->createTeam:102 Team not added
2022-03-04T19:11:30.4465546Z [ERROR]   TeamsPageTest.addUser:112->createTeam:102 Team not added
2022-03-04T19:11:30.4466085Z [ERROR]   TeamsPageTest.checkTeamsFilterCount:214->createTeam:102 Team not added
2022-03-04T19:11:30.4466525Z [ERROR]   TeamsPageTest.createTeam:102 Team not added
2022-03-04T19:11:30.4467234Z [ERROR]   TeamsPageTest.editDescription:148->createTeam:102 Team not added
2022-03-04T19:11:30.4483251Z [ERROR]   TeamsPageTest.ownerNameIsConsistentCheck:195->addAsset:166->createTeam:102 Team not added
2022-03-04T19:11:30.4484889Z [ERROR] Errors: 
2022-03-04T19:11:30.4497903Z [ERROR]   CommonTests.overviewLinksAfterTour:317 » Timeout Expected condition failed: wa...
2022-03-04T19:11:30.4498745Z [ERROR]   CommonTests.tourStepSkippingCheck:329 » Timeout Expected condition failed: wai...
2022-03-04T19:11:30.4499483Z [ERROR]   DatabaseServicePageTest.checkIngestionTab:141 » Timeout Expected condition fai...
2022-03-04T19:11:30.4500133Z [ERROR]   MyDataPageTest.checkFollowingTab:260 » NoSuchElement no such element: Unable t...
2022-03-04T19:11:30.4500758Z [ERROR]   RolesPageTest.checkDuplicateRoleName:206 » Timeout Expected condition failed: ...
2022-03-04T19:11:30.4501355Z [ERROR]   RolesPageTest.editDescription:107 » Timeout Expected condition failed: waiting...
2022-03-04T19:11:30.4501991Z [ERROR]   TableDetailsPageTest.checkBreadCrumb:275 » NoSuchElement no such element: Unab...
2022-03-04T19:11:30.4502653Z [ERROR]   TableDetailsPageTest.checkFrequentlyJoinedColumns:320 » Timeout Expected condi...
2022-03-04T19:11:30.4505288Z [ERROR]   TableDetailsPageTest.checkFrequentlyJoinedTables:309 » Timeout Expected condit...
2022-03-04T19:11:30.4506187Z [ERROR]   TagsPageTest.TagUsageCheck:239 » Timeout Expected condition failed: waiting fo...
2022-03-04T19:11:30.4506929Z [ERROR]   TagsPageTest.removeTagWithExistingName:254 » Timeout Expected condition failed...
2022-03-04T19:11:30.4507601Z [ERROR]   TeamsPageTest.teamsWithSameDisplayNameCheck:251 » NoSuchElement no such elemen...
2022-03-04T19:11:30.4508280Z [ERROR]   TopicDetailsPageTest.checkFollow:112 » NoSuchElement no such element: Unable t...
2022-03-04T19:11:30.4508934Z [ERROR]   TopicDetailsPageTest.checkManage:198 » ElementClickIntercepted element click i...
2022-03-04T19:11:30.4509669Z [INFO] 
2022-03-04T19:11:30.4510096Z [ERROR] Tests run: 161, Failures: 16, Errors: 14, Skipped: 0
```

2022-03-04 20:36 UTC, vivekratnavel commented
I have opened https://github.com/open-metadata/OpenMetadata/issues/3158 to fix Selenium test failures

2022-03-04 20:37 UTC, vivekratnavel approved these changes

2022-03-04 20:37 UTC, merged