Fix #3332: fixed varbyte & time issue
open-metadata/OpenMetadata pull request #3401
Opened 2022-03-14 12:09 UTC by ulixius9

### Describe your changes :

Fix #3332: fixed varbyte & time issue

#
### Type of change :

- [x] Bug fix
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/39544459/158169151-96cc214f-9c8c-4eeb-a57c-e7e1a4f9e215.png">

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@harshach @ayush-shah @pmbrull

2022-03-14 13:35 UTC, ayush-shah approved these changes

2022-03-14 14:07 UTC, pmbrull requested changes
Thanks, @ulixius9, for the PR. One comment here would be that the function feels super complicated. I've seen that when handling a lot of the internal logic in the ingestion module we end up having big nested logics that are hard to understand, which makes them hard to maintain and debug.

Could we try to break this process down into smaller, more manageable and unit-tested functions? Let's try to spend a bit more time on improving the codebase in terms of overall readability and testing.

If this is urgent to deliver for some users, please feel free to merge it, but then open a separate issue to try to improve this.

Thanks!

2022-03-14 14:07 UTC, pmbrull commented on ingestion/src/metadata/ingestion/source/redshift.py
> +    def _handle_array_type(attype):
Why are we defining this function inside the body?

2022-03-15 08:10 UTC, pmbrull reviewed
Thanks for the changes! If possible, please add some unit tests on the individual functions, which will help us evolve the code and showcase what is going on 🙏

2022-03-15 14:13 UTC, pmbrull approved these changes
As with the other PR, let's proceed with pending further work on unit testing. Once SonarCloud correctly collects data, let's iterate over all connectors. Thanks!

2022-03-15 14:18 UTC, merged