Added fix for Airflow Pipeline status
open-metadata/OpenMetadata pull request #3603
Opened 2022-03-22 20:34 UTC by ayush-shah

### Describe your changes :

fix #3581
fix #3557

#
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have performed a self-review of my own. 
- [x] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@harshach @darth-coder00

2022-03-22 20:34 UTC, harshach approved these changes

2022-03-23 01:35 UTC, harshach requested changes
@ayush-shah can you address the code smell by defining the constant

2022-03-23 04:39 UTC, ShaileshParmar11 approved these changes

2022-03-23 06:28 UTC, harshach approved these changes

2022-03-23 07:28 UTC, ayush-shah commented
@parthp2107 @kshinde2512 The Selenium tests are failing.
Merging this PR as the tests failing are not related to the PR.

2022-03-23 07:28 UTC, merged