Fix UI Error Handling on pipeline entity page
open-metadata/OpenMetadata pull request #3649
Opened 2022-03-24 16:39 UTC by Sachin-chaurasiya

See #3380 
### Describe your changes :

I worked on UI Error Handling for pipeline entity page

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have performed a self-review of my own. 
- [ ] I have tagged my reviewers below.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@shahsank3t, @darth-coder00 @vivekratnavel  @ShaileshParmar11

2022-03-24 17:24 UTC, vivekratnavel requested changes

2022-03-25 12:56 UTC, darth-coder00 requested changes
One change suggested

2022-03-25 12:56 UTC, darth-coder00 commented on openmetadata-ui/src/main/resources/ui/src/utils/StringsUtils.ts
> +};
```suggestion
export const getErrorText = (value: AxiosError | string, fallbackText: string) => {
  return (isString(value) ? value : value.response?.data?.message) || fallbackText;
};
```

2022-03-25 19:21 UTC, darth-coder00 requested changes
@Sachin-chaurasiya LGTM!, Let's add some unit tests to support these error handling changes before we merge it in

2022-03-26 13:52 UTC, Sachin-chaurasiya commented
> @Sachin-chaurasiya LGTM!, Let's add some unit tests to support these error handling changes before we merge it in

@darth-coder00 , we can merge this PR and In my next patch I will add the unit tests to support these error handling.

2022-03-26 17:15 UTC, darth-coder00 approved these changes
As discussed, Unit tests to be added in next patch

2022-03-26 17:16 UTC, darth-coder00 commented
@vivekratnavel @harshach please can you review and merge this if looking good.

2022-03-28 05:37 UTC, vivekratnavel approved these changes

2022-03-28 06:05 UTC, vivekratnavel commented
@harshach Can you merge this?

2022-03-29 04:55 UTC, merged