multiple-database-support-added
open-metadata/OpenMetadata pull request #3777
Opened 2022-03-31 04:19 UTC by codingwithabhi

### Describe your changes :

I worked on adding multiple database support in Postgres.
fix #3732 
#
### Type of change :

- [x] Improvement
- [x] New feature
#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.

#
### Reviewers
@harshach @ayush-shah @pmbrull

2022-03-31 05:27 UTC, pmbrull commented
shall we wait for the service.db.schema PR for these changes? @harshach

2022-03-31 06:13 UTC, ayush-shah requested changes

2022-03-31 06:13 UTC, ayush-shah commented on ingestion/src/metadata/ingestion/source/postgres.py
> +        return f"{service_name}.{self.config.database}_{schema}.{table_name}"
Once the fqnSeparator changes are in - can you add FQNseparator instead of "." and remove the usage of underscore and add FQNseparator.

2022-03-31 06:13 UTC, ayush-shah commented on ingestion/src/metadata/ingestion/source/postgres.py
> +            name=self.config.database + "_" + schema.replace(".", "_DOT_"),
Same change here as well

2022-03-31 06:13 UTC, ayush-shah commented on ingestion/src/metadata/ingestion/source/postgres.py
> +            name=self.config.database + "_" + schema.replace(".", "_DOT_"),
can we also remove replace method as it is handled

2022-04-07 15:16 UTC, harshach commented
@codingwithabhi can we merge this in?

2022-04-08 04:35 UTC, ayush-shah commented
@codingwithabhi let's add postgres schema fix inside this PR and merge it in today

2022-04-08 05:19 UTC, pmbrull commented on ingestion/src/metadata/ingestion/source/postgres.py
> +        return f"{service_name}{FQDN_SEPARATOR}{self.config.database}{FQDN_SEPARATOR}{schema}{FQDN_SEPARATOR}{table_name}"
Let's remove this and not pass any FQN when creating the Table entity 🙏

2022-04-09 09:41 UTC, ayush-shah approved these changes

2022-04-09 09:41 UTC, merged