snowflake-connector-fix
open-metadata/OpenMetadata pull request #3885
Opened 2022-04-06 12:13 UTC by codingwithabhi

### Describe your changes :

I worked on the fixing snowflake connector.
#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.

#
### Reviewers
@harshach @ayush-shah @pmbrull

2022-04-06 12:21 UTC, pmbrull requested changes
Thanks for the PR, small comment to maintain a consistent style

2022-04-06 12:21 UTC, pmbrull commented on ingestion/src/metadata/ingestion/source/snowflake.py
> +        config_dict = config.serviceConnection.__root__.config.dict()
let's try to not convert to `dict`if possible. `connectionArguments` is an attribute of `SnowflakeConnection` which has `None` as default, so we should be good to go with:

```
connection_arguments = config.serviceConnection.__root__.config.connectionArguments
if connection_arguments:
    ...
```

2022-04-07 10:56 UTC, pmbrull requested changes

2022-04-07 10:56 UTC, pmbrull commented on ingestion/src/metadata/ingestion/source/snowflake.py
> +        return f"{service_name}{FQDN_SEPARATOR}{self.config.serviceConnection.__root__.config.database}{FQDN_SEPARATOR}{schema}{FQDN_SEPARATOR}{table_name}"
Let's remove the FQN computation on the source. Not needed for the backend.

2022-04-07 10:56 UTC, pmbrull commented on ingestion/src/metadata/ingestion/source/sql_source.py
> +                    if self.source_config.schemaFilterPattern.includes:
Use the filter module here https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/utils/filters.py

2022-04-07 10:56 UTC, pmbrull commented on ingestion/src/metadata/ingestion/source/sql_source.py
> +                    if self.source_config.schemaFilterPattern.includes:
nvm, all this addition can be removed. It is done at line 246!

2022-04-07 15:44 UTC, pmbrull approved these changes
Thanks for the changes. LGTM. Let's merge it in after checking the conflicts

2022-04-08 04:38 UTC, ayush-shah commented
@codingwithabhi prioritize this connector and let's try to merge it in asap

2022-04-08 07:58 UTC, merged