azuresql-connector-fix-added
open-metadata/OpenMetadata pull request #3903
Opened 2022-04-07 05:18 UTC by codingwithabhi

### Describe your changes :

I worked on the fixing Azure SQL connector
#
### Type of change :

- [x] Bug fix
- [x] Improvement

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
#
### Reviewers

2022-04-08 04:35 UTC, ayush-shah commented
is this ready for review?

2022-04-09 19:11 UTC, harshach approved these changes

2022-04-11 10:27 UTC, pmbrull requested changes

2022-04-11 10:27 UTC, pmbrull commented on ingestion/src/metadata/utils/source_connections.py
> -    return url
Is this correct? Looks like it could break Databricks

2022-04-11 16:27 UTC, merged