Fixed my-data asset icons and other UI adjustments
open-metadata/OpenMetadata pull request #3916
Opened 2022-04-07 13:27 UTC by darth-coder00

### Describe your changes :

I worked on fixing icons and adjusting UI for the same

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">
<img width="297" alt="Screenshot 2022-04-07 at 6 55 27 PM" src="https://user-images.githubusercontent.com/86726556/162209582-509ba88e-002f-4bbd-909a-2aec8d906b6e.png">
<img width="212" alt="Screenshot 2022-04-07 at 6 55 48 PM" src="https://user-images.githubusercontent.com/86726556/162209594-2982d240-25f1-495d-9f3a-a4f2edf54fbd.png">
<img width="35" alt="Screenshot 2022-04-07 at 6 56 13 PM" src="https://user-images.githubusercontent.com/86726556/162209596-38f3c6fb-dda5-4b18-b28a-4bf4192acd49.png">

</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@harshach @vivekratnavel @Sachin-chaurasiya @ShaileshParmar11

2022-04-07 15:48 UTC, ShaileshParmar11 approved these changes
LGTM!

2022-04-07 17:23 UTC, vivekratnavel requested changes

2022-04-07 17:23 UTC, vivekratnavel commented on openmetadata-ui/src/main/resources/ui/src/components/RecentSearchedTerms/RecentSearchedTerms.tsx
> +                {/* <FontAwesomeIcon
Can we remove this if we are not using it?

2022-04-07 18:25 UTC, Sachin-chaurasiya approved these changes

2022-04-08 15:25 UTC, vivekratnavel approved these changes

2022-04-08 15:25 UTC, merged