ISSUE-1072: Add Apache Pinot support
open-metadata/OpenMetadata pull request #4649
Opened 2022-05-03 08:06 UTC by MilanBariya

### Describe your changes :

I worked on Adding Apache Pinot support
fix #1072 

#
### Type of change :

- [x] New feature

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2022-05-03 08:25 UTC, ulixius9 requested changes
Added few review comments, also can you please add the unit test for source_connection url.

2022-05-03 08:25 UTC, ulixius9 commented on catalog-rest-service/src/main/resources/json/schema/entity/services/connections/database/pinotdbConnection.json
> +      "enum": ["Pinotdb"],
let's follow the same naming convention that we are using for other connector,
can you please rename `Pinotdb` to `PinotDB`. (Ex: [MariaDB](https://github.com/open-metadata/OpenMetadata/blob/7f323e5ecc9670bf3fd6a1fd803abd887d066ede/catalog-rest-service/src/main/resources/json/schema/entity/services/databaseService.json#L25), [DynamoDB](https://github.com/open-metadata/OpenMetadata/blob/7f323e5ecc9670bf3fd6a1fd803abd887d066ede/catalog-rest-service/src/main/resources/json/schema/entity/services/databaseService.json#L30))

2022-05-03 08:25 UTC, ulixius9 commented on catalog-rest-service/src/main/resources/json/schema/entity/services/connections/database/pinotdbConnection.json
> +      "enum": ["pinot"],
pinotdb also supports the schema `pinot+http` & `pinot+https`, let's add that to the enum as well

2022-05-09 06:47 UTC, pmbrull commented on catalog-rest-service/src/main/resources/json/schema/entity/services/databaseService.json
> +              "$ref": "./connections/database/pinotDBConnection.json"
This reference is failing due to the filename. The filename should be `pinotDBConnection.json`.

2022-05-11 08:35 UTC, ulixius9 approved these changes

2022-05-11 09:12 UTC, pmbrull approved these changes

2022-05-11 09:13 UTC, merged