[Backend][SAML] SAML Support
open-metadata/OpenMetadata pull request #5852
Opened 2022-07-05 12:30 UTC by mohityadav766

### Describe your changes :

Saml support #2664

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/open-source-community/developer) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2022-09-12 03:22 UTC, harshach commented on catalog-rest-service/src/main/java/org/openmetadata/catalog/CatalogApplication.java
> +    SamlSettingsHolder.getInstance().initDefaultSettings(catalogConfig);
we should only add these settings if the catalogConfig has same settings

2022-09-12 03:23 UTC, harshach commented on catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/UserResource.java
> +    return Response.status(200).build();
we are not doing anything here?

2022-09-12 03:23 UTC, harshach commented on catalog-rest-service/src/main/java/org/openmetadata/catalog/security/JwtFilter.java
> +    if (providerType.equals("saml") || providerType.equals("basic")) {
please add final strings for all the constants

2022-09-12 03:23 UTC, harshach commented on catalog-rest-service/src/main/java/org/openmetadata/catalog/security/JwtFilter.java
> +    if (uriInfo.getPath().contains("logout") && (providerType.equals("saml") || providerType.equals("basic"))) {
same here

2022-09-12 03:23 UTC, harshach commented on catalog-rest-service/src/main/java/org/openmetadata/catalog/security/jwt/JWTTokenGenerator.java
> +              .withClaim("sub", userName)
same

2022-09-12 03:24 UTC, harshach commented on catalog-rest-service/src/main/java/org/openmetadata/catalog/resources/teams/UserResource.java
> +    return Response.status(200).build();
why not invalidate the token here?

2022-09-12 03:24 UTC, harshach requested changes
@mohitdeuex left few comments take a look

2022-11-17 03:23 UTC, harshach commented
@mohityadav766 guessing this is not needed. Closing.

2022-11-17 03:23 UTC, closed without merging

2022-11-17 10:28 UTC, dpadmor commented
@harshach why is not needed ??