Fix #7239 Backend: Add validations for teamType patch
open-metadata/OpenMetadata pull request #7321
Opened 2022-09-07 22:48 UTC by vivekratnavel

### Describe your changes :
See #7239 

#
### Type of change :

- [x] Improvement

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2022-09-08 16:23 UTC, nahuelverdugo approved these changes

2022-09-12 03:08 UTC, harshach commented on catalog-rest-service/src/main/java/org/openmetadata/catalog/exception/CatalogExceptionMessage.java
> +  public static String invalidGroupTeamUpdate() {
do we need a method call, lets make them static final strings no?

2022-09-12 03:08 UTC, harshach requested changes
lets remove method calls

2022-09-12 21:13 UTC, harshach approved these changes

2022-09-12 21:28 UTC, merged