UI :- Added option to remove owner
open-metadata/OpenMetadata pull request #8087
Opened 2022-10-11 13:05 UTC by Ashish8689

### Describe your changes :

- Issue : Closes 
- Added option to remove owner

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
<img width="602" alt="image" src="https://user-images.githubusercontent.com/66266464/195098664-b531cd58-7365-4688-8c61-0deb362963a4.png">

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

2022-10-12 01:21 UTC, harshach commented
@Ashish8689 while we are on this PR can we add an option to remove Tier as well

2022-10-12 04:36 UTC, Ashish8689 commented
@harshach  ok, will add a option for Tier too!

2022-10-17 11:27 UTC, chirag-madlani requested changes

2022-10-17 11:27 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
> +    return Promise.reject();
Why we need this?

2022-10-17 11:27 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/common/TierCard/TierCard.tsx
> +            </Typography.Title>
Row must have Col as children

2022-10-17 11:27 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/DatabaseSchemaPage/DatabaseSchemaPage.component.tsx
> +            reject();
It should be resolved right?

2022-10-17 11:27 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/database-details/index.tsx
> +            reject();
`resolve()`??

2022-10-17 11:27 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
> +            return resolve();
I don't think we need to return just `resolve()` will work

2022-10-17 11:27 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
> +          return reject();
same as above

2022-10-17 11:27 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/service/index.tsx
> +          return reject();
same as above

2022-10-18 12:34 UTC, chirag-madlani approved these changes

2022-10-18 12:34 UTC, merged