Issue 7948
open-metadata/OpenMetadata pull request #8259
Opened 2022-10-19 13:18 UTC by YuexinChen96

### Describe your changes :

I worked on adding a Loader when fetching the data in ElasticSearch because it costs some time when fetching data with empty data displayed.

#
### Type of change :

- [] Bug fix
- [x] Improvement
- [] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2022-10-26 12:53 UTC, harshach commented
@chirag-madlani review please

2022-10-30 10:14 UTC, YuexinChen96 commented
@chirag-madlani Hi Chirag, I added the Loader to the project and reviewed the failing tests. It seems like it is not caused by my change. Please check, or I will close this pull request.

2022-10-30 11:11 UTC, chirag-madlani requested changes
Please rebase your branch with latest main to fix failing checks.
Sorry for the delay in response

2022-10-30 11:11 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/elastic-search-index.page.tsx
> +            {streamLoading ? <Loader size="small" type="white" /> : ''}
```suggestion
            {batchLoading ? <Loader size="small" type="white" /> : ''}
```

2022-11-04 11:55 UTC, YuexinChen96 commented
I have tried to merge to the main branch and create a new pull request.

2022-11-04 11:55 UTC, closed without merging