Test Dashboard Services!
open-metadata/OpenMetadata pull request #8287
Opened 2022-10-20 11:17 UTC by Supzz2

### Describe your changes :

I worked on the test Dashboard Service because close issue #3187

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2022-10-23 14:26 UTC, pmbrull commented
hi @Supzz2 thanks for the PR. Please take a look at the python checkstyle failures. You can fix that by running `make py_format`. Thanks

2022-10-24 15:46 UTC, harshach approved these changes

2022-10-26 12:58 UTC, TeddyCr requested changes
@Supzz2 it looks like you copied and pasted the database service test. We need to implement a test for the dashboard service

2022-10-29 12:26 UTC, Supzz2 commented
I don't plan to continue updating this PR, so I will close it.

2022-10-29 12:26 UTC, closed without merging