Fix #8901 UI : Show bot user roles on bot detail page
open-metadata/OpenMetadata pull request #8922
Opened 2022-11-21 11:58 UTC by Sachin-chaurasiya

### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2022-11-21 16:17 UTC, ShaileshParmar11 reviewed
added some comments

2022-11-21 16:17 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +          label: getEntityName(role as unknown as EntityReference),
is it necessary to typecase a role? can we give role type in getEntityName

2022-11-21 16:17 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +    if (!isAdminUser && !isAuthDisabled) {
can we make this condition truthy?

2022-11-21 16:17 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +                  placeholder="Roles..."
localization!

2022-11-21 16:17 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +                        className="tw-w-3.5 tw-h-3.5"
lets use our own class, wherever its possible

2022-11-21 16:17 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/styles/spacing.less
> +}
instead of this you can use m-l-xs // 8px

2022-11-21 16:17 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/styles/spacing.less
> +}
m-b-xss -> 4px

2022-11-22 08:56 UTC, chirag-madlani requested changes

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/BotDetailsPage/BotDetailsPage.tsx
> +          isAuthDisabled={Boolean(isAuthDisabled)}
values which are accessed via context why are we passing as props?

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +  isAuthDisabled,
We should access this via context instead getting it as props

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +  const DisplayNameComponent = ({
If it's a component add it to separate file instead part of other component

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +      />
Since we aren't manipulating anything here use <Description /> directly to the render.
remove `DescriptionComponent` we don't need it

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +  const InheritedRolesComponent = ({
Can we make this as common component instead copy paste it from somewhere?

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +  const RolesComponent = ({ roles, botUserData }: RolesComponentProps) => {
Can we make this as common component instead copy paste it from somewhere?

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.component.tsx
> +  const RolesElement = ({ botUserData }: RolesElementProps) => (
Can we make this as common component instead copy paste it from somewhere?

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.style.less
> +  }
Try to use icon size prop instead manipulating icon this way

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/BotDetails/BotDetails.style.less
> +}
I feel we have common styling for `Card` Please check if we can use them

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/Users/Users.component.tsx
> +        <div className="tw-flex tw-items-center tw-justify-between">
Get rid of tailwind classes

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
> +    "displayName": "displayName"
use `kabab-case` only for localisation keys

2022-11-22 08:56 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/styles/app.less
> +}
Too much open CSS are you intent to update it globally?

2022-11-22 13:07 UTC, Sachin-chaurasiya commented
@chirag-madlani, All comments are addressed.

2022-11-22 13:15 UTC, chirag-madlani approved these changes

2022-11-22 13:58 UTC, ShaileshParmar11 approved these changes

2022-11-22 14:15 UTC, merged