kpi resource test task done
open-metadata/OpenMetadata pull request #9006
Opened 2022-11-25 06:51 UTC by 07Himank

### Describe your changes :

I worked on Kpi resource test.

# 
### Type of change :

- [x] Bug fix

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@mohityadav766

2022-11-25 10:38 UTC, mohityadav766 commented on openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
> +import static org.openmetadata.service.Entity.*;
avoid wild card imports

2022-11-25 10:38 UTC, mohityadav766 commented on openmetadata-service/src/test/java/org/openmetadata/service/resources/EntityResourceTest.java
> +import static org.openmetadata.service.exception.CatalogExceptionMessage.*;
remove wild card imports

2022-11-25 10:38 UTC, mohityadav766 commented on openmetadata-service/src/test/java/org/openmetadata/service/resources/events/WebhookResourceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
same

2022-11-25 10:38 UTC, mohityadav766 commented on openmetadata-service/src/test/java/org/openmetadata/service/resources/events/WebhookResourceTest.java
> +import org.openmetadata.schema.type.*;
wild card -

2022-11-25 10:39 UTC, mohityadav766 commented on openmetadata-service/src/test/java/org/openmetadata/service/resources/kpi/KpiResourceTest.java
> +            .withName("TestChart" + UUID.randomUUID())
can use String.format

2022-11-28 09:15 UTC, nahuelverdugo requested changes

2022-11-28 09:15 UTC, nahuelverdugo commented on openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/KpiRepository.java
> +      updateToRelationships(
Why have we done this change from `updateFromRelationships` to `updateToRelationships`? The PR says: `add KPI resource test`.

2022-11-28 09:20 UTC, nahuelverdugo commented on openmetadata-service/src/main/java/org/openmetadata/service/jdbi3/KpiRepository.java
> +      updateToRelationships(
Reviewed with @mohityadav766

2022-11-28 09:23 UTC, merged