Fix #8846 : Replace Reviewer and deploy ingestion with antd modal in the UI
open-metadata/OpenMetadata pull request #9076
Opened 2022-11-30 11:46 UTC by Sachin-chaurasiya

### Describe your changes :

I worked on issue #8846 and Replaced Reviewer and deploy ingestion with antd modal in the UI

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

2022-11-30 13:40 UTC, chirag-madlani approved these changes

2022-12-01 05:30 UTC, ShaileshParmar11 requested changes

2022-12-01 05:30 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/postgres.spec.js
Please avoid exist and forceClick

2022-12-01 11:27 UTC, ShaileshParmar11 requested changes
Please update all the places
- we must `be.visible` instead of `exist`
- avoid force click

2022-12-01 11:27 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
> +    cy.get('[data-testid="delete-confirmation-modal"]').should('exist');
please update to `be.visible`

2022-12-01 11:27 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
> +      .contains('PersonalData')
we should category with tag, please revert the change

2022-12-01 11:27 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
> +        cy.get('[data-testid="add-tag"]').should('exist').click()
remove exist and use visible

2022-12-01 11:27 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/cypress/e2e/Pages/Glossary.spec.js
> +    cy.get('[data-testid="glossary-left-panel"]').should('exist').contains(NEW_GLOSSARY.name);
Why we are making this change?

2022-12-02 16:14 UTC, ShaileshParmar11 approved these changes

2022-12-02 16:15 UTC, merged