UI : Revamp Teams page
open-metadata/OpenMetadata pull request #9107
Opened 2022-12-01 16:08 UTC by Ashish8689

### Describe your changes :

- Closes : #8170
- Breadcrumb: Each team will have its parent teams 
- Redesign Team Table
- Shift Show Deleted switch in Dropdown

#
### Type of change :

- [x] Bug fix
- [x] Improvement

#
### Frontend Preview (Screenshots) :
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/66266464/205101771-fdc6f905-a191-4fdb-8cc0-2ebe17f7254b.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/66266464/205101899-cb9f407e-a9ab-4900-a330-9435ab8883be.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/66266464/205102024-d7a78f1c-4198-4409-b204-a95055fd712e.png">

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

2022-12-01 16:24 UTC, harshach commented
@Ashish8689 can we add "Asset Count" as another column in the teams page
cc @chirag-madlani

2022-12-01 16:29 UTC, Ashish8689 commented
@harshach yes,will add that too.

2022-12-01 16:47 UTC, chirag-madlani requested changes

2022-12-01 16:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
> +  const DELETED_TEAMS_ITEM = [
```suggestion
  const MORE_OPTIONS = [
```

2022-12-01 16:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
> +      ),
I will we can simplify this DOM

2022-12-01 16:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
> +  const organizationDropdownContent = <Menu items={[...DELETED_TEAMS_ITEM]} />;
```suggestion
  const organizationDropdownContent = <Menu items={DELETED_TEAMS_ITEM} />;
```

Avoid unnecessary spreading

2022-12-01 16:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
> +  const DELETED_TEAMS_ITEM = [
Remove array and just assign item directly & call it `DELETED_TOGGLE_MENU_ITEM`

2022-12-01 16:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
> +  const organizationDropdownContent = <Menu items={[...DELETED_TEAMS_ITEM]} />;
Now it will be `items={[DELETED_TOGGLE_MENU_ITEM]}`

2022-12-01 16:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamHierarchy.tsx
> +                alt="icon"
We can remove this if not needed, "Icon" doesn't make any sense

2022-12-01 16:47 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/styles/components/table.less
> +  .ant-table-thead {
If wanted to update global attach more screenshots in the PR

2022-12-02 05:04 UTC, Ashish8689 commented
@harshach Added an asset count column that falls under their team, please verify this and do let me know if changes are required. 
 
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/66266464/205218284-92afeb8e-be22-40c3-8221-e2cf1ffccf4e.png">

2022-12-02 07:40 UTC, Ashish8689 commented
@chirag-madlani @aniketkatkar97 all changes have been addressed.

2022-12-02 08:29 UTC, chirag-madlani submitted a review, later dismissed

2022-12-02 10:16 UTC, ShaileshParmar11 commented
Please resolve the conflict!

2022-12-02 12:50 UTC, chirag-madlani approved these changes

2022-12-02 12:53 UTC, merged