Dbt workflow
open-metadata/OpenMetadata pull request #9178
Opened 2022-12-06 16:11 UTC by OnkarVO7

### Describe your changes :

Fix https://github.com/open-metadata/OpenMetadata/issues/9024

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

@open-metadata/ingestion

2022-12-08 08:56 UTC, TeddyCr commented
@OnkarVO7 are you able to fix sonar and the checkstyle? 🙂

2022-12-08 10:13 UTC, OnkarVO7 commented
> @OnkarVO7 are you able to fix sonar and the checkstyle? 🙂

Yes @TeddyCr will do that

2022-12-12 10:31 UTC, pmbrull requested changes
Let's create a single DBT source instead of having to replicate the same class for each DB source. The logic is the same so we should be good to go with a single class.

Thanks

2022-12-12 12:31 UTC, OnkarVO7 commented on ingestion/src/metadata/utils/dbt_config.py
> +        if config.dbtCatalogFilePath is not None and config.dbtCatalogFilePath != "":
Yes right will handle this

2022-12-12 12:44 UTC, OnkarVO7 commented on openmetadata-spec/src/main/resources/json/schema/metadataIngestion/databaseServiceMetadataPipeline.json
> -    "dbtConfigSource": {
@nahuelverdugo will add it thanks

2022-12-12 12:46 UTC, OnkarVO7 commented on ingestion/src/metadata/ingestion/source/database/dbt_source.py
> +        pass
@nahuelverdugo we do not need to to test connection for DBT since it doesn't connect to any source

2022-12-12 13:16 UTC, nahuelverdugo commented on ingestion/src/metadata/ingestion/source/database/dbt_source.py
> +        pass
Can we add at least a comment on the method with the reason for passing it?

2022-12-12 13:46 UTC, OnkarVO7 commented on ingestion/src/metadata/ingestion/source/database/dbt_source.py
> +        pass
Will add it

2022-12-14 05:46 UTC, OnkarVO7 commented on ingestion/src/metadata/ingestion/source/database/dbt.py
> +class DbtSource(DbtServiceSource, ABC):  # pylint: disable=too-many-public-methods
It will not be let me change that

2022-12-15 17:07 UTC, OnkarVO7 commented
Closing this PR due to a lot of conflicts and difficult to resolve this. Opened a separate PR which has all the changes with this one
https://github.com/open-metadata/OpenMetadata/pull/9302

2022-12-15 17:07 UTC, closed without merging