UI :- Added Data Insights in elasticsearch for re-indexing
open-metadata/OpenMetadata pull request #9292
Opened 2022-12-14 13:08 UTC by Ashish8689

### Describe your changes :

- Issue :- #9289
- Added Data Insights in elasticsearch for re-indexing

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :
<img width="770" alt="image" src="https://user-images.githubusercontent.com/66266464/207614853-078cdbbc-1ec6-488f-ab85-8e4056dd9f43.png">

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
 @open-metadata/ui

2022-12-14 13:38 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/constants/elasticsearch.constant.ts
> +  },
Please confirm name with @ShilpaVernekar once!

2022-12-14 13:42 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/ElasticSearchReIndexModal.component.tsx
> +                <Col key={option.value} span={8}>
@Ashish8689 can you also make re-create index initial value to `true`?

2022-12-14 14:01 UTC, Ashish8689 commented
@ShaileshParmar11 @chirag-madlani Changes updated!

2022-12-14 14:02 UTC, chirag-madlani requested changes

2022-12-14 14:02 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/pages/ElasticSearchIndexPage/ElasticSearchReIndexModal.component.tsx
> +        <Form.Item initialValue label="Recreate indexes" name="recreateIndex">
localisation please

2022-12-14 14:02 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/constants/elasticsearch.constant.ts
> +    label: 'Web Analytics Report',
localisation

2022-12-14 14:28 UTC, Ashish8689 commented
@chirag-madlani added localisation in the files.

2022-12-14 14:30 UTC, chirag-madlani approved these changes

2022-12-14 18:37 UTC, Sachin-chaurasiya approved these changes

2022-12-14 18:41 UTC, chirag-madlani commented
DO NOT MERGE THIS UNTIL BACKEND CHANGES PUSHED 
cc: @mohityadav766

2022-12-22 07:16 UTC, chirag-madlani approved these changes

2022-12-22 07:36 UTC, mohityadav766 commented
Backend side changes are done.  Cc @chirag-madlani

2022-12-22 08:17 UTC, merged