Dbt worflow2
open-metadata/OpenMetadata pull request #9302
Opened 2022-12-15 07:57 UTC by Ashish8689

### Describe your changes :

Fix https://github.com/open-metadata/OpenMetadata/issues/9024
Fix https://github.com/open-metadata/OpenMetadata/issues/5559
Fix https://github.com/open-metadata/OpenMetadata/issues/7038
Fix https://github.com/open-metadata/OpenMetadata/issues/8535

#
### Type of change :

- [x] Improvement
- [x] New feature

#
### Frontend Preview (Screenshots) :

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui 
@open-metadata/backend 
@open-metadata/ingestion

2022-12-15 09:03 UTC, chirag-madlani requested changes

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/cypress.config.ts
> +  defaultCommandTimeout: 50000,
Revert this

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/cypress.config.ts
> +    baseUrl: 'http://localhost:3000',
revert this

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/cypress/common/common.js
> +    // }
Remove this

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/cypress/common/common.js
> +    // configureDBT
remove this

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/redshiftWithDBT.spec.js
> +    // };
Remove this

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/cypress/e2e/AddNewService/redshiftWithDBT.spec.js
> +    //   configureDBT
Remove this

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/AddIngestion/AddIngestion.component.tsx
> +            cancelText="Cancel"
localisation

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTConfigFormBuilder.test.tsx
> +  cancelText: 'Cancel',
localisation

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTConfigFormBuilder.tsx
> +          Name
localisation

2022-12-15 09:03 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/common/DBTConfigFormBuilder/DBTConfigFormBuilder.tsx
> +          Name that identifies this configuration instance uniquely.
localisation

2022-12-15 10:15 UTC, Ashish8689 commented
@chirag-madlani changes made as per comments!

2022-12-15 10:26 UTC, chirag-madlani approved these changes
Looks good on UI side

2022-12-15 13:45 UTC, chirag-madlani approved these changes

2022-12-16 11:30 UTC, ulixius9 approved these changes

2022-12-16 11:30 UTC, merged