UI : Lineage UI improvement
open-metadata/OpenMetadata pull request #9312
Opened 2022-12-15 13:37 UTC by Ashish8689

### Describe your changes :

- Issue : #9001
- Reduce zoom  to 0.5
- Reduce the space between Lineage nodes
- Change the label to display name/name in the search bar lineage

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/66266464/207872816-05c2a1c7-ae37-479a-8b8c-f73892065463.png">

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

2022-12-15 13:40 UTC, Sachin-chaurasiya requested changes

2022-12-15 13:40 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/components/EntityLineage/CustomControls.component.tsx
> +        label: node.displayName || node.name || '',
Can we use `getEntityName` util function here?

2022-12-15 13:44 UTC, chirag-madlani reviewed
Address comment from @Sachin-chaurasiya 
Looks good to me

2022-12-15 13:48 UTC, Ashish8689 commented
@Sachin-chaurasiya  changes made as per comments!

2022-12-16 05:02 UTC, Sachin-chaurasiya approved these changes

2022-12-16 08:38 UTC, merged