UI: Added relative percentage change details in UI
open-metadata/OpenMetadata pull request #9354
Opened 2022-12-16 16:02 UTC by ShaileshParmar11

### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2022-12-16 16:25 UTC, chirag-madlani requested changes

2022-12-16 16:25 UTC, chirag-madlani commented on openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/ChangeInValueIndicator.tsx
> +import React from 'react';
licence

2022-12-16 16:32 UTC, ShaileshParmar11 commented on openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/ChangeInValueIndicator.tsx
> +import React from 'react';
added licence

2022-12-16 16:38 UTC, chirag-madlani submitted a review, later dismissed

2022-12-17 03:53 UTC, harshach commented
@ShaileshParmar11 need to display the percentage at each entity level as well
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/38649/208222445-c6d5b466-7338-4611-88a1-aa5182d50dcc.png">
similar to here

<img width="366" alt="image" src="https://user-images.githubusercontent.com/38649/208222473-15db52d8-cc26-4e4a-baf8-96898fcd9cda.png">

2022-12-18 11:56 UTC, chirag-madlani approved these changes

2022-12-18 11:57 UTC, merged