UI : Added Organization displayName in DataInsight health glance
open-metadata/OpenMetadata pull request #9359
Opened 2022-12-16 17:00 UTC by Ashish8689

### Describe your changes :

- Issue : #8996
- Added Organization displayName in DataInsight health glance

#
### Type of change :

- [x] Improvement

#
### Frontend Preview (Screenshots) :
<img width="870" alt="image" src="https://user-images.githubusercontent.com/66266464/208150077-4c412c39-8390-4a27-99ba-9fd10319beb1.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/66266464/208150137-0c91d977-4274-44d4-9e88-647db38ae18f.png">

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers
@open-metadata/ui

2022-12-16 17:03 UTC, ShaileshParmar11 submitted a review, later dismissed

2022-12-17 05:11 UTC, Sachin-chaurasiya requested changes

2022-12-17 05:11 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightSummary.tsx
> +  );
```suggestion
  const [OrganizationDetails, setOrganizationDetails] = useState<Team>(
  );
```

2022-12-17 05:11 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightSummary.tsx
> +  };
Wrap with try/catch

2022-12-17 05:11 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/components/DataInsightDetail/DataInsightSummary.tsx
> +              OrganizationDetails.displayName || t('label.openMetadata'),
@Ashish8689, We should use `getEntityName` util, so if displayName is not present it fallback to name.

2022-12-17 05:11 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/locale/languages/en-us.json
> +    "openMetadata": "OpenMetadata"
@Ashish8689 , We already have `the "open-metadata"` key, use that.

2022-12-17 07:38 UTC, Ashish8689 commented
@Sachin-chaurasiya  changes made as per comments!

2022-12-17 07:39 UTC, Sachin-chaurasiya approved these changes

2022-12-17 09:00 UTC, ShaileshParmar11 approved these changes

2022-12-17 09:00 UTC, merged