fix(ui): missing localization key for delete widget
open-metadata/OpenMetadata pull request #9600
Opened 2023-01-04 10:59 UTC by chirag-madlani

### Describe your changes :

I worked on the closing: #9607

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2023-01-04 11:50 UTC, Sachin-chaurasiya requested changes

2023-01-04 11:50 UTC, Sachin-chaurasiya commented on openmetadata-ui/src/main/resources/ui/src/components/TeamDetails/TeamDetailsV1.tsx
> +            {t('message.are-you-sure-you-want-to-remove-child-from-parent]', {
```suggestion
            {t('message.are-you-sure-you-want-to-remove-child-from-parent', {
```

2023-01-04 13:35 UTC, Sachin-chaurasiya submitted a review, later dismissed

2023-01-05 04:30 UTC, ShaileshParmar11 approved these changes

2023-01-05 04:30 UTC, merged