Fix: s3 files for parquet
open-metadata/OpenMetadata pull request #9621
Opened 2023-01-05 09:49 UTC by NiharDoshi99

### Describe your changes :

I worked on getting parquet files for s3

#
### Type of change :

- [x] Bug fix
- [ ] Improvement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

2023-01-05 10:57 UTC, ulixius9 requested changes

2023-01-05 10:57 UTC, ulixius9 commented on docker/metadata/docker-compose-postgres.yml
> +    image: openmetadata/ingestion:0.13.1.3
no need to update docker-compose, can you please revert this!

2023-01-06 07:24 UTC, ulixius9 approved these changes

2023-01-06 12:58 UTC, akash-jain-10 approved these changes

2023-01-06 13:01 UTC, merged