Fix #9752: docker openmetadata_ingestion should only depend on db
open-metadata/OpenMetadata pull request #9753
Opened 2023-01-16 23:40 UTC by harshach

### Describe your changes :

I worked on the ..... because ...

#
### Type of change :

- [x] Bug fix
- [x] Improvement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

#
### Frontend Preview (Screenshots) :
<p align="center">For frontend related change, please link screenshots of your changes preview! Optional for backend related changes.
</p>

#
### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://docs.open-metadata.org/developers/contribute) document.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] All new and existing tests passed.

#
### Reviewers

2023-01-17 05:53 UTC, akash-jain-10 approved these changes

2023-01-17 07:00 UTC, sureshms requested changes

2023-01-17 10:25 UTC, pmbrull approved these changes
Added the changes for the local docker as well. LGTM

2023-01-18 06:56 UTC, akash-jain-10 approved these changes

2023-01-18 07:45 UTC, merged